### DISCUSSION TITLE
Help need updating old installation

### DISCUSSION THREAD

**Discussion by gregeeh** [wallabag/wallabag#7517] [Q&A]
Hi all,

I've noticed the environment variables have changed since I installed Wallabag on my NAS.  What do I need to do to bring my installation up to date without losing any data?

About says my version is 2.6.9.

TIA

My present Portainer Stack:

```
services:
### Wallabag ###
  wallabag:
    image: wallabag/wallabag:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=somepassword
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=greg@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.mydomain.com
      - SYMFONY__ENV__SERVER_NAME="My wallabag instance"
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
    ports:
      - '6080:80'
    volumes:
      - /share/appdata/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://127.0.0.1"]
      interval: 1m
      timeout: 3s
    hostname: wallabag.localdomain
    labels:
      - "diun.enable=true"
    networks:
      - wallabag
    restart: unless-stopped
    depends_on:
      - db
      - redis
 ### Mariadb ###
  db:
    image: mariadb:latest
    volumes:
      - /share/appdata/wallabag/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=<wallaroot>"]
      interval: 20s
      timeout: 3s
    networks:
      - wallabag
    restart: unless-stopped
    
### Redis ###
  redis:
    image: redis:alpine
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    volumes:
      - /share/appdata/wallabag/redis/data:/data
    networks:
      - wallabag
    restart: unless-stopped

networks:
  wallabag:
```
