### ISSUE TITLE
Failed to setup via composer

### ISSUE THREAD

**Issue by theonlydoo** [wallabag/wallabag#1772]
### Issue details

```bash

php bin/console wallabag:install --env=prod
PHP Warning:  require(/var/www/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/var/www/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/wallabag/app/autoload.php on line 9
```

### Environment

* wallabag version : e7931dbdf8c045ddc7d1085de0fe084ae001170d
* How did you install wallabag? https://github.com/wallabag/wallabag/blob/v2/README.md#want-to-test-the-v2
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: Wheezy
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Follow the normal setup on debian wheezy with PHP 5.6 via dotdeb 

# PHP 

```bash

# dpkg -l|grep php
ii  dh-php5                                   0.2                                   all          debhelper add-on to handle PHP PECL extensions
ii  libapache2-mod-php5                       5.6.19-1~dotdeb+7.1                   amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libphp-serialization-perl                 0.34-1                                all          Perl module to manipulate serialized PHP data structures
ii  php-pear                                  5.6.19-1~dotdeb+7.1                   all          PEAR - PHP Extension and Application Repository
ii  php5                                      5.6.19-1~dotdeb+7.1                   all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-cli                                  5.6.19-1~dotdeb+7.1                   amd64        command-line interpreter for the php5 scripting language
ii  php5-common                               5.6.19-1~dotdeb+7.1                   amd64        Common files for packages built from the php5 source
ii  php5-curl                                 5.6.19-1~dotdeb+7.1                   amd64        CURL module for php5
ii  php5-dev                                  5.6.19-1~dotdeb+7.1                   amd64        Files for PHP5 module development
ii  php5-fpm                                  5.6.19-1~dotdeb+7.1                   amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php5-gd                                   5.6.19-1~dotdeb+7.1                   amd64        GD module for php5
ii  php5-imap                                 5.6.19-1~dotdeb+7.1                   amd64        IMAP module for php5
ii  php5-mcrypt                               5.6.19-1~dotdeb+7.1                   amd64        MCrypt module for php5
ii  php5-mysql                                5.6.19-1~dotdeb+7.1                   amd64        MySQL module for php5
ii  php5-pgsql                                5.6.19-1~dotdeb+7.1                   amd64        PostgreSQL module for php5
ii  php5-readline                             5.6.19-1~dotdeb+7.1                   amd64        Readline module for php5
ii  php5-sqlite                               5.6.19-1~dotdeb+7.1                   amd64        SQLite module for php5
ii  php5-tidy                                 5.6.19-1~dotdeb+7.1                   amd64        tidy module for php5
ii  pkg-php-tools                             1.21                                  all          various packaging tools and scripts for PHP packages

```

**Comment by tcitworld** [comment]
You did `SYMFONY_ENV=prod composer create-project wallabag/wallabag wallabag "2.0.0-beta.1" --no-dev` first ?
Sounds like composer did not do his job here.

**Comment by theonlydoo** [comment]
Yep, I followed the install procedure! Only on database path, I let SQLite path since i thout it wasn't relevant to the MySQL setup

**Comment by tcitworld** [comment]
Weird.
Does running `composer update` changes things ?

**Comment by theonlydoo** [comment]
I'm currently trying, but really slowed down by all the :


```bash
Could not fetch https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/31f8b717e51d9a2afca6c9f046f5d69fc27c8686, please create a GitHub OAuth token to go over the API rate limit
```

**Comment by tcitworld** [comment]
Yeah, you need to follow the link to create a github token for not being bothered by Github anymore, sorry about this, we're thinking on how we can get rid of this.

**Comment by theonlydoo** [comment]
Ok, after a few `composer update`, i got this : 


```bash
php bin/console wallabag:install --env=prod -vvv
Installing Wallabag...

Step 1 of 4. Checking system requirements.
+-----------------+--------+----------------+
| Checked         | Status | Recommendation |
+-----------------+--------+----------------+
| PDO Drivers     | OK!    |                |
| curl_exec       | OK!    |                |
| curl_multi_init | OK!    |                |
+-----------------+--------+----------------+
Success! Your system can run Wallabag properly.

Step 2 of 4. Setting up database.
Creating database and schema, clearing the cache
The command "doctrine:database:create" terminated with an error code: 1.

                                                                            
  [Exception]                                                               
  The command "doctrine:database:create" terminated with an error code: 1.  
                                                                            

Exception trace:
 () at /var/www/wallabag/src/Wallabag/CoreBundle/Command/InstallCommand.php:413
 Wallabag\CoreBundle\Command\InstallCommand->runCommand() at /var/www/wallabag/src/Wallabag/CoreBundle/Command/InstallCommand.php:144
 Wallabag\CoreBundle\Command\InstallCommand->setupDatabase() at /var/www/wallabag/src/Wallabag/CoreBundle/Command/InstallCommand.php:61
 Wallabag\CoreBundle\Command\InstallCommand->execute() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:807
 Symfony\Component\Console\Application->doRunCommand() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/wallabag/bin/console:29
```

**Comment by tcitworld** [comment]
Since you use SQLite for the database, could you make sure you have the rights to write inside this repository ?

**Comment by theonlydoo** [comment]
I don't want to use SQLite, I tried to setup with mysql :

```yaml
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: mydatabase
    database_user: mydatabase
    database_password: mypassword
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    test_database_driver: pdo_sqlite
    test_database_host: 127.0.0.1
    test_database_port: null
    test_database_name: null
    test_database_user: null
    test_database_password: null
    test_database_path: '%kernel.root_dir%/../data/db/wallabag_test.sqlite'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
```
