### ISSUE TITLE
White screen after installation

### ISSUE THREAD

**Issue by pyrophyllit** [wallabag/wallabag#2146]
I have massive problems installing wallabag with MySQL. 

I am facing the problem now that I can only see a white screen in my brwoser after installing everything as explanined. 

My parameters.yml looks like that:

```yaml
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag_admin
    database_password: ***********
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    database_path: null
    database_table_prefix: wallabag_
    locale: en
    secret: null
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
```

Any help is much appreciated! And please update the documentation for the installation of wallabag as many people seem to complain about it.
