### ISSUE TITLE
Redis using unix socket

### ISSUE THREAD

**Issue by das-schaf** [wallabag/wallabag#2391]
### Issue details

The current redis implementation only supports using redis via tcp. My hoster instead only allows using redis via unix socket. Is it possible to support unix sockets for redis?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1
* How did you install wallabag? package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0
* OS: centos
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by j0k3r** [comment]
This shouldn't be hard to enable.

If you need it right away, you can edit `/src/Wallabag/CoreBundle/Resources/config/services.yml` at line 118, replace the redis config by:

```yaml
    wallabag_core.redis.client:
        class: Predis\Client
        arguments:
            -
                scheme: 'unix'
                path: '/path/to/redis.socket'
```

It should work.
