### ISSUE TITLE
Upgrade fails with non-existent parameter error

### ISSUE THREAD

**Issue by mbrandis** [wallabag/wallabag#2539]
### Issue details

After upgrade on shared hosting, error message of unknown parameter is thrown.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2 and 2.1.3
* How did you install wallabag? Via `git clone` or by downloading the package? Downloaded shared package
* Last wallabag version that did not exhibit the issue (if applicable): 2.1.1
* php version: 5.6.27
* OS: Debian stable
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Tried to upgrade from 2.1.1 to 2.1.3 based on the upgrade documentation. After upgrade the following error message can be seen in Apache log:

PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException' with message 'You have requested a non-existent parameter "database_port". Did you mean one of these: "database_host", "database_name", "database_user", "database_path"?'

Then tried to upgrade to 2.1.2 first, got a similar but different message:

PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException' with message 'You have requested a non-existent parameter "database_socket". Did you mean one of these: database_driver", "database_host", "database_port", "database_name", "database_user"?'

Any ideas what the problem could be?

**Comment by nicosomb** [comment]
Hello @mbrandis! 

[As explained in the documentation](http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.1.html#upgrade-on-a-shared-hosting), your `app/config/parameters.yml` file needs to have some values. 
But we forgot to update the documentation for some values, like `database_socket`. 

Here is the good default `parameters.yml` file: 

```
    parameters:
        database_driver: pdo_sqlite
        database_host: 127.0.0.1
        database_port: null
        database_name: symfony
        database_user: root
        database_password: null
        database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
        database_table_prefix: wallabag_
        database_socket: null
        mailer_transport: smtp
        mailer_host: 127.0.0.1
        mailer_user: null
        mailer_password: null
        locale: en
        secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv
        twofactor_auth: true
        twofactor_sender: no-reply@wallabag.org
        fosuser_registration: true
        fosuser_confirmation: true
        from_email: no-reply@wallabag.org
        rss_limit: 50
        rabbitmq_host: localhost
        rabbitmq_port: 5672
        rabbitmq_user: guest
        rabbitmq_password: guest
        redis_scheme: tcp
        redis_host: localhost
        redis_port: 6379
        redis_path: null
```

Be sure to have all the required parameters.
