### ISSUE TITLE
wallabag on shared server (strato.de) using mysql, access denied for user

### ISSUE THREAD

**Issue by aisbergde** [wallabag/wallabag#2925]
### Issue details
when I execute

```
php bin/console wallabag:install --env=prod
```

I can't connect to the database

```
Installing wallabag...

Step 1 of 4. Checking system requirements.
+------------------------+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Checked                | Status | Recommendation                                                                                                                                                        |
+------------------------+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PDO Driver (pdo_mysql) | OK!    |                                                                                                                                                                       |
| Database connection    | ERROR! | Can't connect to the database: An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'U1234567'@'aklathep.store.d0m.de' (using password: YES) |
| Database version       | OK!    |                                                                                                                                                                       |
| curl_exec              | OK!    |                                                                                                                                                                       |
| curl_multi_init        | OK!    |                                                                                                                                                                       |
+------------------------+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

What is the @'aklathep.store.d0m.de' after the user name? (I replaced the real user name U....... by U1234567 here in the issue)

### Environment

* wallabag version (or git revision) that exhibits the issue: 
latest-v2-package
* How did you install wallabag? 
wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: ?
* type of hosting (shared):
* which storage system you choose at install (MySQL 5.6.35):

### Steps to reproduce/test case
use provider strato.de
follow the description here:
https://faq2.mstyle-online.de/wallabag-installation-shared-hosting-strato/
create a new mysql database
test the access to this database via SSH 
wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
rename download folder into "wallabag"
edit the file parameters.yml in app/config:
(change database_driver, database_host, database_name, database_user and database_password)
execute
php bin/console wallabag:install --env=prod

**Comment by j0k3r** [comment]
Could you please share your `app/config/parameters.yml`?

**Comment by aisbergde** [comment]
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: rdbms.strato.de
    database_port: null
    database_name: DB1234567
    database_user: U1234567
    database_password: Abc123
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: thisisnottheoriginal
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sites_credentials: {  }

```	
	
I also tried
    database_port: 3306
