### ISSUE TITLE
Migration script assumes quote table names are enabled for MySQL

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3036]
_From @shikasta-net on April 10, 2017 10:18_

I run Wallabag in docker and was trying to upgrade 2.0.8 to 2.1.6 but had the following problem:

> -> ALTER TABLE "wallabag_entry" ADD uuid LONGTEXT DEFAULT NULL
Migration 20160410190541 failed during Execution. Error An exception occurred while executing 'ALTER TABLE "wallabag_entry" ADD uuid LONGTEXT DEFAULT NULL':

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"wallabag_entry" ADD uuid LONGTEXT DEFAULT NULL' at line 1

This was similar to the issue described in [issue 2364](https://github.com/wallabag/wallabag/issues/2364) but with MySQL.  Eventually I realised the issue was with double quotes around the table names.  I resolved the upgrade by logging into MySQL and running `SET GLOBAL SQL_MODE=ANSI_QUOTES` before performing the production migration.  Reverting the setting after migration doesn't seem to cause a problem (yet).

I have a common database server for several services so I don't want to globally change behaviour.  Could the migration script do a session level `SET SQL_MODE=ANSI_QUOTES` before running its commands to ensure the migration works as designed?

_Copied from original issue: wallabag/docker#62_

**Comment by j0k3r** [comment]
I wasn't aware of that sql mode .. :man_facepalming:

**Comment by j0k3r** [comment]
_From @xsteadfastx on April 10, 2017 12:7_

Is that a docker problem?

**Comment by j0k3r** [comment]
I don't think so.

**Comment by aaa2000** [comment]
Maybe, could be resolved by use dbal option and `PDO::MYSQL_ATTR_INIT_COMMAND`

```
# Doctrine Configuration
doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: "%database_charset%"
        path: "%database_path%"
        unix_socket: "%database_socket%"
        server_version: 5.6
        options:
            # PDO::MYSQL_ATTR_INIT_COMMAND
            1002: "SET SQL_MODE=ANSI_QUOTES"
```
