### ISSUE TITLE
#article_toolbar in hardcopy printouts must die

### ISSUE THREAD

**Issue by jn0** [wallabag/wallabag#311]
I suppose something like that:

``` css
@media print {
        #article_toolbar { display: none; }
}
```

But there are still shaded lines on the bottom of almost any page...
