### ISSUE TITLE
Syntax error when installing

### ISSUE THREAD

**Issue by jonazc** [wallabag/wallabag#3470]
### Issue details
I tried to install Wallabag using `git clone` and then `make install`. As `pdo_driver` I set `pdo_mysql`. It also looks fine, that composer can connect to the DB, but then there appears a syntax error for the DB create:

```
Step 1 of 4. Checking system requirements.
+------------------------+--------+----------------+
| Checked                | Status | Recommendation |
+------------------------+--------+----------------+
| PDO Driver (pdo_mysql) | OK!    |                |
| Database connection    | OK!    |                |
| Database version       | OK!    |                |
| curl_exec              | OK!    |                |
| curl_multi_init        | OK!    |                |
+------------------------+--------+----------------+
Success! Your system can run wallabag properly.

Step 2 of 4. Setting up database.
Creating database and schema, clearing the cache

The command "doctrine:database:create" generates some errors: 
Could not create database /var/www/virtual/user/walla.example.com/app/../data/db/wallabag.sqlite for connection named default
An exception occurred while executing 'CREATE DATABASE /var/www/virtual/user/walla.example.com/app/../data/db/wallabag.sqlite':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/var/www/virtual/user/walla.example.com/app/../data/db/wallabag.sqlite' at line 1
```
I cant understand, why composer still wants to create a sqlite file and work with it when I already have chosen `pdo_mysql` as driver?

### Environment
* git master
* php version: PHP 7.1.12
* OS: Cent OS 6
* type of hosting (shared or dedicated): shared
* DB: MariaDB

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
Could you share your `app/config/parameters.yml` file?

**Comment by tcitworld** [comment]
It seems like it's trying to install to sqlite instead of MariaDB. If you previously selected the sqlite setup, you need to clear cache `rm -rf /var/www/virtual/user/walla.example.com/var/cache/*`

**Comment by jonazc** [comment]
@tcitworld no that can't be, I didn't choose sqlite before, it was a fresh installation. But I was still asked after I chose `pdo_mysql` what the path of the DB file should be, I just left the default because the question was nonsense while there is no DB file for mysql. That file is actually the one that the error complains about now:

`database_path ('%kernel.root_dir%/../data/db/wallabag.sqlite'):`

**Comment by jonazc** [comment]
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3307
    database_name: xxxx
    database_user: xxxx
    database_password: xxxx
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: xxxx
    twofactor_auth: false
    twofactor_sender: xxxx
    fosuser_registration: false
    fosuser_confirmation: false
    from_email: xxxx
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sites_credentials: {  }

```
