### ISSUE TITLE
Installation fails with error: [RuntimeException] 

### ISSUE THREAD

**Issue by cmonty14** [wallabag/wallabag#3748]
### Issue details

After completing all preparation steps (DB setup, etc.) I started `make install` in directory /var/www/wallabag.

After a few seconds I get this error:
````
Wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------ -------- ----------------------------------------------------------------------------------------------------------
  Checked                  Status   Recommendation                                                                                 
 ------------------------ -------- ----------------------------------------------------------------------------------------------------------
  PDO Driver (pdo_mysql)   OK!                                                                                                     
  Database connection      ERROR!   Can't connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused
  Database version         OK!                                                                                                     
  curl_exec                OK!                                                                                                     
  curl_multi_init          OK!                                                                                                     
 ------------------------ -------- ----------------------------------------------------------------------------------------------------------

15:07:45 ERROR     [console] Error thrown while running command "wallabag:install --env=prod". Message: "Some system requirements are not fulfilled. Please check output messages and fix them." ["error" => RuntimeException { …},"command" => "wallabag:install --env=prod","message" => "Some system requirements are not fulfilled. Please check output messages and fix them."] []


  [RuntimeException]
  Some system requirements are not fulfilled. Please check output messages and fix them.


wallabag:install [--reset] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

make: *** [Makefile:13: install] Error 1
````

This error message points to an issue with DB connect.

However I can connect to the DB w/o issues:
````
ct120-devbag:/var/www/wallabag# mysql -u wb --password=40Er5pp5Kmnp3 wallabag
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.3.9-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [wallabag]> show tables;
+--------------------+
| Tables_in_wallabag |
+--------------------+
|                                |
+--------------------+
0 row in set (0.000 sec)

````

### Environment

* wallabag version (or git revision) that exhibits the issue: 
latest git
* How did you install wallabag? Via `git clone` or by downloading the package?
git clone
* php version:
PHP 7.2.11 (cli) (built: Oct 11 2018 17:56:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies
* OS:
Alpine Linux 3.8
* type of hosting (shared or dedicated):
dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
Maria DB 10.3.9

### Steps to reproduce/test case

run `make install` in /var/www/wallabag

This is my configuration:
````
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_driver_class: null
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wb
    database_password: 40Er5pp5Kmnp3
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://devbag.mydomain.de'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: root
    mailer_password: null
    locale: de
    secret: ovmpmAWXRCabNlMgzlzFxxxxxxxxxx
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
````

How can I further analyse this issue to identify the root cause?

THX
