### ISSUE TITLE
Importing Pocket stuff Could Error: "not convert database value "a:1:{i:0;s:26:"M. J" to Doctrine Type array"

### ISSUE THREAD

**Issue by de-ramon** [wallabag/wallabag#3873]
Hi,

I just installed wallabag on a shared hoster (mysql 5.7.21-nmm1-log utf8mb4_unicode_ci  / PHP 7.1) using ssh like here:
https://doc.wallabag.org/de/admin/installation/installation.html

```
wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package

# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_driver_class: null
    database_host: 127.0.0.1
    database_port: null
    database_name: d02dxxx
    database_user: d02dxxx
    database_password: 1234 :-)
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: https://rddddddd
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: de
    secret: ovmpmAWXRCabNl--
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
```

Importing my  Pocket stuff starts and then:

```
https://rdltr.afadfads/import/pocket/callback
500: Internal Server Error
Could not convert database value "a:1:{i:0;s:26:"M. J" to Doctrine Type array
```

Is my charset ok?
database_charset: utf8mb4

thx,
de_ramon
