### ISSUE TITLE
After upgradign: You have requested a non-existent parameter "database_driver_class".  Did you mean this: "database_driver"?

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#3913]
### Issue details

After upgrading to 2.3.7 according to wiki I see white page instead of login screen.
```
PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException: You have requested a non-existent parameter "database_driver_class". 
Did you mean this: "database_driver"? in /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100\nStack trace:\n#0 /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get('database_driver...')\n#1 /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(217): Symfony\\Component\\DependencyInjection\\ParameterBag\\EnvPlaceholderParameterBag->get('database_driver...')\n#2 /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->resolveStri in /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
```
I tried to downgrade to 2.3.6 still same issue

### Environment

* wallabag version 2.3.6 and 2.3.7 shared hosting
* How did you install wallabag? package
* Last wallabag version that did not exhibit the issue (if applicable): sorry I didn't check before upgrade 
* php version: php7.3.3
* OS: debian 8
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

download zip
unpack zip
overwrite old data
copy parameters and data/
clean var/cache
try to enter page with wallabag

**Comment by bigretromike** [comment]
Is this issue with php 7.3 ? as the support from symphony was confirmed recently?: https://github.com/symfony/symfony/issues/29579

**Comment by j0k3r** [comment]
I don't think it's related to the PHP version.
Can you show us your `app/config/parameters.yml` file?

**Comment by bigretromike** [comment]
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: <removed_for_issue>
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    database_charset: utf8
    rabbitmq_prefetch_count: 10
    redis_password: null
    domain_name: 'https://<removed_for_issue>'
```
