### ISSUE TITLE
Material Icons aren't shown. Instead there is only Text

### ISSUE THREAD

**Issue by TheLux83** [wallabag/wallabag#4122]
### Issue details

Hey there. I've deployed your wallabag docker instance into a new server, but for some reason, it cannot load the icons on the page like add, search etc.
I've found out that these seems to be material icons, but I don't know how to repair this issue.
I've already removed the container and deleted the volume, but that didn't helped.
Without these icons, everything overlaps and I cannot use wallabag :-(

### Environment

* wallabag version (or git revision) that exhibits the issue: **Version: 2.3.8**
* How did you install wallabag? Via `git clone` or by downloading the package? ** Via Docker Instance**
* Last wallabag version that did not exhibit the issue (if applicable): **2.3.8 (On my old server, I don't have this problem)**
* php version:
* OS: 
* type of hosting (shared or dedicated): **vServer**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **SQLite**

### Steps to reproduce/test case

I just deployed the docker instance with this compose code:
```
  wallabag:
    container_name: wallabag
    network_mode: bridge
    restart: always
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__MAILER_HOST=mail.example.com
      - SYMFONY__ENV__MAILER_USER=wallabag@example.com
      - SYMFONY__ENV__MAILER_PASSWORD=supercoolsecretpassword
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.com
    ports:
      - "80"
    volumes:
      - /path/to/wallabag/images:/var/www/wallabag/web/assets/images
      - /path/to/wallabag/data:/var/www/wallabag/data
```
Maybe you can help me with my problem?
If you need more information, please ask.

Thanks in advange and cheers.
