### ISSUE TITLE
Extend access token

### ISSUE THREAD

**Issue by joshp23** [wallabag/wallabag#4292]
I have an external app that runs a housekeeping routine every hour. The Wallabag access token that my app holds needs to be updated with this housekeeping routine. I need the Wallabag access token to last longer than the hour. Is there a way to extend the life of the access token that Wallabag provides?

**Comment by joshp23** [comment]
Found this:
In the file `app/config/config.yml`, find the following section and add the final line:
```
fos_oauth_server:
    service:
        options:
            access_token_lifetime: 7200
```
run the following in Wallabag's root folder
```
 sudo -u www-data php ./bin/console cache:clear -e prod 
```
Would it be possible to include this as a configurable option, generally?
