### ISSUE TITLE
Error on Instapaper import

### ISSUE THREAD

**Issue by jrozelle** [wallabag/wallabag#4420]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Error on import :

> 500: Internal Server Error
> 
> An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Qu'y a-t-il dans mon sac photo ? - photoetmac.com", "http:\/\/photoetmac.com\/2016\/07\/quy-a-t-sac-photo\/", 0, 0, "wallabag can't retrieve contents for this article. Please <a href=\"http:\/\/doc.wallabag.org\/en\/user\/errors_during_fetching.html#how-can-i-help-to-fix-that\">troubleshoot this issue<\/a>.\n", "2020-05-28 09:40:16", "2020-05-28 09:40:16", null, "N;", null, null, null, 0, "photoetmac.com", null, "Unread", "N;", null, 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'http_status' at row 1

If I enable asynchronous mode, import is stuck. I don't know how to "reset" import queue

### Environment

docker-compose on private docker.

```
  wallabag:
    image: wallabag/wallabag
    restart: always
    container_name: wallabag
    depends_on:
      - wallabag-db
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=passwd
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=https://bag.domain.tld
      - TZ=Europe/Paris
    volumes:
      - ./wallabag/images:/var/www/wallabag/web/assets/images
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.bag.rule: Host(`bag.domain.tld`)
      traefik.http.routers.bag.tls.certresolver: acmegandi
      traefik.http.routers.bag.tls.domains[0].main: "domain.tld"
      traefik.http.routers.bag.tls.domains[0].sans: "*.domain.tld"
    mem_limit: 256M
      
  wallabag-db:
    image: mariadb:latest
    restart: always
    container_name: wallabag-db
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Europe/Paris
    volumes:
      - ./wallabag/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 256M  
      
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment: 
      TZ: "Europe/Paris"
    mem_limit: 512M
```

### Steps to reproduce/test case

Just docker-compose up -d and import from Instapaper
