### ISSUE TITLE
Not loading database parameters.yml and using the default ones

### ISSUE THREAD

**Issue by fabiodcorreia** [wallabag/wallabag#4451]
### Issue details
When executing `wallabag:install` returns the error `Can't connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused` during system checks.

```
Step 1 of 4: Checking system requirements.

|  ------------------------ -------- ---------------------------------------------------------------------------------------------------------- 
|   Checked                  Status   Recommendation                                                                                            
|  ------------------------ -------- ---------------------------------------------------------------------------------------------------------- 
|   PDO Driver (pdo_mysql)   OK!                                                                                                                
|   Database connection      ERROR!   Can't connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused  
|   Database version         OK!                                                                                                                
|   curl_exec                OK!                                                                                                                
|   curl_multi_init          OK!                                                                                                                
```

When I run `doctrine:migrations:migrate` with vvv I see this line on the file `/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43`
```php
$dsn: "mysql:host=127.0.0.1;dbname=wallabag;charset=utf8mb4;"
```
even if the parameters.yml have this values:
```yml
parameters:
    database_driver: pdo_mysql
    database_driver_class: null
    database_host: 'mariadb_wallabag'
    database_port: 'null'
    database_name: 'wallabagdb'
    database_user: 'wallabaguser'
    database_password: 'wallabagpass'
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
```
So I made my won PDOConnection.php with this hardcoded values
```php
parent::__construct("mysql:host=mariadb_wallabag;dbname=wallabagdb;charset=utf8mb4;", "wallabaguser", "wallabagpass", $options);
```
and during the container entrypoint execution I replace the file inside the container with this hardcoded and it works!! Looks like the parameters.yml it not getting loaded for some reason but I know almost zero about PHP and PHP Frameworks :(

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.3.8**
* How did you install wallabag? Via `git clone` or by downloading the package?: **Package**
* Last wallabag version that did not exhibit the issue (if applicable): **N/A**
* php version: **7.3.19**
* OS: Alpine **3.12**
* type of hosting (shared or dedicated): **Docker**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **MariaDB**

### Steps to reproduce/test case
I follow the steps on the official docker image, except I replaced the ansible provisioning with manual provisioning since I want to create the DB and user outside of the docker container.

It's not working but I think I can provide my docker repo on github if required.
