### ISSUE TITLE
Docker: General error: 1 no such table: wallabag_internal_setting

### ISSUE THREAD

**Issue by kayloehmann** [wallabag/wallabag#4819]
### Issue details

Please provide issue details here.
After upgrade to 2.4.0 i have the following issue in the logs and the login screen is blank:
2020/12/11 08:50:12 [error] 248#248: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67

### Environment

* wallabag version (or git revision) that exhibits the issue:
2.4.0

* How did you install wallabag? Via `git clone` or by downloading the package?
docker image

* Last wallabag version that did not exhibit the issue (if applicable):
2.3.8

* php version:
as in official docker

* OS:
Synology NAS

* type of hosting (shared or dedicated):
home nas

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

**Comment by Kdecherf** [comment]
@kayloehmann how did you update the version?

**Comment by kayloehmann** [comment]
Automatically through Watchtower: https://hub.docker.com/r/v2tec/watchtower/

**Comment by Kdecherf** [comment]
The Docker image does not currently handle migrations when upgrading, please check these steps: https://github.com/wallabag/docker#upgrading

**Comment by diegombeltran** [comment]
I think I have the same problem here. Trying to fix it by using:
`php bin/console doctrine:migrations:migrate --env=prod`

Results in:
![imagen](https://user-images.githubusercontent.com/7081281/101885089-eef4fc80-3b99-11eb-9f2f-2e22faa2e873.png)

**Comment by diegombeltran** [comment]
> The Docker image does not currently handle migrations when upgrading, please check these steps: https://github.com/wallabag/docker#upgrading

Looks like I didn't do this for a long time and something bad happens when trying to upgrade the schema, although it should not.

**Comment by j0k3r** [comment]
@diegombeltran could you share your `app/config/parameters.yml`?

**Comment by kayloehmann** [comment]
> The Docker image does not currently handle migrations when upgrading, please check these steps: https://github.com/wallabag/docker#upgrading

Thanks for the fast replies everyone, this worked for me. :-)

**Comment by diegombeltran** [comment]
Sure (Changed sensitive data with MyWhatever)
```
This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_host: postgresql
    database_port: 5432
    database_name: databaseName
    database_user: databaseUser
    database_password: databasePassword
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://mydomain.com'
    mailer_transport: smtp
    mailer_user: mySMTPUser
    mailer_password: mySMTPPassword
    mailer_host: mySMTPPort
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: mySecret
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: my@email.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```

Also my ENV variables while deploying are:

```
POSTGRES_USER=MyUser
POSTGRES_PASSWORD=MyPassword
SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
SYMFONY__ENV__DATABASE_DRIVER_CLASS=Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
SYMFONY__ENV__DOMAIN_NAME=https://mydomain.com
SYMFONY__ENV__DATABASE_HOST=postgresql
SYMFONY__ENV__DATABASE_PORT=5432
SYMFONY__ENV__DATABASE_NAME=MyDB
SYMFONY__ENV__DATABASE_USER=MyUser
SYMFONY__ENV__DATABASE_PASSWORD=MyPass
SYMFONY__ENV__MAILER_HOST=MySMTP
SYMFONY__ENV__MAILER_USER=MySMTPUser
SYMFONY__ENV__MAILER_PASSWORD=MySMTPPass
SYMFONY__ENV__FROM_EMAIL=my@email.com
SYMFONY__ENV__FOSUSER_REGISTRATION=false
SYMFONY__ENV__FOSUSER_CONFIRMATION=false
#SYMFONY__ENV__TWOFACTOR_AUTH=false
```
