### ISSUE TITLE
Android and ios apps stopped receiving the article list after upgrade to 2.4.0

### ISSUE THREAD

**Issue by Pitstopper** [wallabag/wallabag#4849]
### Environment

* **Version**: 2.4.0
* **Installation**: git clone
* **PHP version**: 7.4.13
* **OS**: Debian 10
* **Database**: MySQL/MariaDB
* **Parameters**: <details>
  <summary>Your `app/config/parameters.yml` below</summary>

  ```
  parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: xxxxxxxxxxxxxxx
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'xxxxxxxxxxxxxx'
    mailer_transport: gmail
    mailer_user: xxxxxxxxxxxxxxx
    mailer_password: xxxxxxxxxxxxxxx
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: xxxxxxxxxxxxxxxxxxxx
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

After upgrading the server to version 2.4.0, the wallabag android and ios apps stopped receiving the article list. The login is correct, but none of the lists are loaded.

**/var/logs/prod.log:**

[2020-12-15 14:23:03] request.INFO: Matched route "api_get_entries". {"route":"api_get_entries","route_parameters":{"_controller":"Wallabag\ApiBundle\Controller\EntryRestController::getEntriesAction","_format":"json","_route":"api_get_entries"},"request_uri":"https://xxx.xxx.co/api/entries.json?detail=full&order=asc&page=1&perPage=30&since=0&sort=created","method":"GET"} []
[2020-12-15 14:23:04] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getType" of class "ReflectionProperty"." at /var/www/wallabag/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php line 107 {"exception":"[object] (Symfony\Component\Debug\Exception\UndefinedMethodException(code: 0): Attempted to call an undefined method named "getType" of class "ReflectionProperty". at /var/www/wallabag/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php:107)"} []
