### ISSUE TITLE
ARM 7 Docker image needed to run on Raspberry Pi models. 

### ISSUE THREAD

**Issue by krswin** [wallabag/wallabag#4872]
ARM 7 Docker image needed to run on Raspberry Pi models. 
Thanks

**Comment by maguilara** [comment]
If you feel confident enough, follow this guide: https://www.dahl-jacobsen.dk/tips/blog/2017-10-18-wallabag/
I was able to setup wallabag using this docker-compose configuration, haven't testest mariadb/mysql (not interested either)
```
version: '3'
services:
  wallabag:
    image: wallabag   #custom image built using the guide
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.0.140:8080 # ip address of your raspberry and port specified below
    ports:
      - "8080:80"
    volumes:
      - ${ROOT_DOCKER}/wallabag/images:/var/www/wallabag/web/assets/images
    restart: unless-stopped
```
