### ISSUE TITLE
Error: Table 'wallabag.wallabag_internal_setting' doesn't exist

### ISSUE THREAD

**Issue by leolivier** [wallabag/wallabag#4923]
### Environment

* **Version**: 2.4.0
* **Installation**: Built the "standard" docker image on RPi (can be found at https://hub.docker.com/repository/docker/leolivier/wallabag)
* **PHP version**:
* **OS**: Raspian Buster
* **Database**: should be MariaDB (latest docker image from yobasystems/alpine-mariadb),  but path in parameters seems to be sqlite see below
* **Parameters**:
<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: 'xxxxxxxxx'
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'xxx'
    mailer_transport: smtp
    mailer_user: xxx
    mailer_password: ***
    mailer_host: xxx
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr_FR
    secret: '***'
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@levillain.ml
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

 * **docker-compose.yml**:
<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>

```
version: '3'
services:
  wallabag:
    container_name: wallabag
    image: leolivier/wallabag:armv7-rpi
    build: /hdd/dev/docker/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=****
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__SECRET=***
      - SYMFONY__ENV__LOCALE=fr_FR
      - SYMFONY__ENV__MAILER_HOST=xxx
      - SYMFONY__ENV__MAILER_USER=xxx
      - SYMFONY__ENV__MAILER_PASSWORD=***
      - SYMFONY__ENV__FROM_EMAIL=xxx
      - SYMFONY__ENV__DOMAIN_NAME=xxx
    ports:
      - "192.168.1.8:11080:80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    restart: always
  db:
    container_name: wallabag.db
    image: yobasystems/alpine-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=***
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/restore:/restore
    restart: always
```
</details>

### What steps will reproduce the bug?

This install is working since 2 years now but recently I noticed the login page was blank and I found in the logs:
`2021/01/09 18:26:21 [error] 272#272: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_internal_setting' doesn't exist in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129`

I checked the tables in my database:

```
Tables_in_wallabag
migration_versions
wallabag_annotation
wallabag_config
wallabag_craue_config_setting
wallabag_entry
wallabag_entry_tag
wallabag_oauth2_access_tokens
wallabag_oauth2_auth_codes
wallabag_oauth2_clients
wallabag_oauth2_refresh_tokens
wallabag_site_credential
wallabag_tag
wallabag_tagging_rule
wallabag_user
```
So, nothing looking like 'wallabag_internal_settings'.
And, something weird is the content of the parameters: I have a pdo_mysql driver (as required in the docker-compose.yml) but a database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite' (maybe this is ignored in the case of a mariadb database?)

Anyway, this was working before but maybe I switched to a new version of Mailu w/o noticing it (I monthly automatically pull the git repo and rebuild) and I should have migrated something?
