### ISSUE TITLE
Error login with app and extension

### ISSUE THREAD

**Issue by lazerleif** [wallabag/wallabag#4945]
### Environment

* **Version**: 2.4.1
* **Installation**: git clone
* **PHP version**: 7.4
* **OS**: Ubuntu 20.04
* **Database**: PostgreSQL
* **Parameters**: 

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: XXX
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: UTF8
    domain_name: 'XXX'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: XXX
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    server_name: XXX
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Trying to connect to my wallabag instance after upgrade to 2.4. Chrome and Firefox extension just gives error. And android app says: API access test failed No access to API: {"error":"access_denied","error_description":"OAuth2 authentication required"}

I have 2fa disabled as you see in parameter.yml. Tried to clear cache and reinstall but i still get same error. Tried to create a new user aswell.

edit: from prod.log
[prod.log](https://github.com/wallabag/wallabag/files/5821842/prod.log)
