### ISSUE TITLE
500 internal server error: Attempted to call function "token_get_all" from the global namespace

### ISSUE THREAD

**Issue by myuseraccount** [wallabag/wallabag#4964]
I did a fresh install by git clone of version 2.4.1, on FreeBSD with Ngnix and PHP 7.3.  Using dbo_sqlite for the database.

I can log in as Admin, but when I try to create a user account manually and click the Save button after filling out the page, I get the following error:

500: Internal Server Error

Attempted to call function "token_get_all" from the global namespace.

Sorry, I'd include a log entry, but I can't seem to find anything in my logs about this request or error.

**Comment by j0k3r** [comment]
Could you please not removing the template defined when you create an issue? It helps us.

**Comment by myuseraccount** [comment]
Sorry, didn't see that the first time for some reason!


### Environment

* **Version**: 2.4.1
* **Installation**: git clone
* **PHP version**: 7.3
* **OS**: FreeBSD 12.2
* **Database**: Sqlite 3.33.0
* **Parameters**:  
<details>
  <summary>My <code>app/config/parameters.yml</code> is:

</summary>

  ```
 parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://[REDACTED].net'
    server_name: 'My library'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: [REDACTED]
    twofactor_auth: false
    twofactor_sender: no_reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no_reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null



  ```
</details>

### What steps will reproduce the bug?

1. Log in as admin
2. choose Users Management
3. click CREATE A NEW USER
4. fill out details
5. click SAVE

Also results in same error:

1.  At login page, click REGISTER
(goes immediately to the same error message)
