### ISSUE TITLE
Update breaking on PHP 8

### ISSUE THREAD

**Issue by opsydev** [wallabag/wallabag#4987]
### Environment

* **Version**: 2.4.1 or master
* **Installation**: Git Clone on a VPS
* **PHP version**: PHP 8.0
* **OS**: Ubuntu 20.04
* **Database**: Postgresql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: xxxxxxxx
    database_user: xxxxxxxx
    database_password: xxxxxxxx
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://xxxxxxxx'
    mailer_transport: smtp
    mailer_host: xxxxxxxx
    mailer_user: xxxxxxxx
    mailer_password: xxxxxxxx
    locale: en
    secret: xxxxxxxx
    twofactor_auth: true
    twofactor_sender: xxxxxxxx
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: xxxxxxxx
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: xxxxxxxx
    rabbitmq_password: xxxxxxxx
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    server_name: 'xxxxxxxx xxxxxxxx'
  ```
</details>

### What steps will reproduce the bug?
Upgrade Ubuntu to use system PHP 8.0. Run the wallabag `make update`

It breaks because of Doctrine issues, the following error shows up:

```
  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:



  PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /path/to/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 81

  In PDOConnection.php line 81:

    Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() m
    ust be compatible with PDO::query(string $query, ?int $fetchMode = null, mi
    xed ...$fetchModeArgs)
```

Looks like this was fixed with https://github.com/doctrine/dbal/pull/3803 but the wallabag dependencies are still referring to v2.x of dbal. Can we update the dependencies to resolve the issue?

Thanks,
