### ISSUE TITLE
update  2.3.8 to 2.4.1 (docker image)

### ISSUE THREAD

**Issue by levasbr1** [wallabag/wallabag#4990]
### Environment

* **Version**: 2.4.1
* **Installation**: Docker
* **PHP version**: N/A
* **OS**: Debian
* **Database**: SQLite
* **Parameters**: N/A

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
docker-compose.yml
version: '3'
services:
  wallabag:
    image: wallabag/wallabag:2.4.1
    container_name: wallabag_app
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      - SYMFONY__ENV__MAILER_HOST=smtp.exemple.com:587
      - SYMFONY__ENV__MAILER_USER=user@exemple.com
      - SYMFONY__ENV__MAILER_PASSWORD=p4ssw0rd
      - SYMFONY__ENV__FROM_EMAIL=noreply@exemple.com
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.exemple.com
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.routers.wallabagnotls.rule=Host(`wallabag.exemple.com`)"
      - "traefik.http.routers.wallabagnotls.entrypoints=webinsecure"
      - "traefik.http.routers.wallabagnotls.middlewares=tlsredir@file"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.exemple.com`)"
      - "traefik.http.routers.wallabag.entrypoints=websecure"
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.http.routers.wallabag.tls.certresolver=letsencrypt"

    expose:
      - "80"
    volumes:
      - data:/var/www/wallabag/data
      - img:/var/www/wallabag/web/assets/images
    restart: unless-stopped
    networks:
      - traefik_lan

  redis:
    image: redis:alpine
    container_name: wallabag_cache
    volumes:
      - cache:/data
    networks:
      - traefik_lan
    restart: unless-stopped

networks:
  traefik_lan:
    external: true

volumes:
  data:
  img:
  cache:
  ```
</details>

### What steps will reproduce the bug?

When I update the docker image (2.3.8 to 2.4.1), I get a blank page with in the logs: 

```
PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67
```
