### ISSUE TITLE
Can't set up Wallabag in Docker or VM because of database creation issues

### ISSUE THREAD

**Issue by andre-dierker** [wallabag/wallabag#4992]
### Environment

* **Version**: latest git and docker versions
* **Installation**: git clone and Docker (compose) - I tired both
* **PHP version**: 7.4, version in Docker not known
* **OS**: Debian 10 & Docker
* **Database**: mysql & sqlite on host and mysql in docker
* **Parameters**: standard

My app/config/parameters.yml

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: root
    database_password: null
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://your-wallabag-url-instance.com'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: something random
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```

### What steps will reproduce the bug?

I wondered where my pretty old Wallabag docker installation went and it was broken. I decided to do a new installation and run into an issue while creating the database. I experienced the same problem in a docker compose installation (Wallabag, Database, Redis) and in a installation on a virtual machine. On the virtual Machine I tried a installation with Mysql driver and one with SQLite with the very same result.

Looks like the issue is not new: https://github.com/wallabag/wallabag/issues/4037

```
Step 3 of 4: Administration setup.
----------------------------------

 Would you like to create a new admin user (recommended)? (yes/no) [yes]:
 > yes

 Username [wallabag]:
 > andre

 Password [wallabag]:
 > 

 Email [wallabag@wallabag.io]:
 > mail@mail.mail


In AbstractSQLiteDriver.php line 46:
                                                                                                       
  An exception occurred while executing 'INSERT INTO "wallabag_user" (username, username_canonical, e  
  mail, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_  
  at, roles, name, created_at, updated_at, authCode, googleAuthenticatorSecret, backupCodes, emailTwo  
  Factor) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':                              
                                                                                                       
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_user                                       
                                                                                                       
In PDOConnection.php line 72:
                                                                  
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_user  
                                                               
In PDOConnection.php line 67:
                                                                  
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_user  

```

It differs only from the database driver. Same results in Docker and git installation.

same if I run *php bin/console wallabag:clean-downloaded-images --env=prod --dry-run*

```
andre@walla:~/wallabag$ php bin/console wallabag:install --env=prod

wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------- -------- ---------------- 
  Checked                   Status   Recommendation  
 ------------------------- -------- ---------------- 
  PDO Driver (pdo_sqlite)   OK!                      
  Database connection       OK!                      
  Database version          OK!                      
  curl_exec                 OK!                      
  curl_multi_init           OK!                      
 ------------------------- -------- ---------------- 

                                                                                                        
 [OK] Success! Your system can run wallabag properly.                                                   
                                                                                                        

Step 2 of 4: Setting up database.
---------------------------------

 Creating database and schema, clearing the cache

Step 3 of 4: Administration setup.
----------------------------------

 Would you like to create a new admin user (recommended)? (yes/no) [yes]:
 > andre

Step 4 of 4: Config setup.
--------------------------


In AbstractSQLiteDriver.php line 46:
                                                                                    
  An exception occurred while executing 'DELETE FROM "wallabag_internal_setting"':  
                                                                                    
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting        
                                                                                    

In PDOConnection.php line 46:
                                                                              
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting  
                                                                              

In PDOConnection.php line 41:
                                                                              
  SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting  
```

It looks like the installer misses to create the database or tables?

Regards
André
