### ISSUE TITLE
material-icons doesn't show up.

### ISSUE THREAD

**Issue by mfriedrichs** [wallabag/wallabag#4993]
Installed: I installed Wallabag as an Synology (NAS) DSM Service (Not the Docker-Version, but a regular DSM-Service). 
OS: The host is some *nix/ linux but i dont know exactly what this Synology Distribution is derived from.
DB: MySQL

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
 parameters:
    database_driver: pdo_mysql
    database_driver_class: ~
    database_host: 127.0.0.1
    database_port: 3307
    database_name: wallabag
    database_user: wallabag
    database_password: 140972bB!w
    # For SQLite, database_path should be "%kernel.project_dir%/data/db/wallabag.sqlite"
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    # with PostgreSQL and SQLite, you must set "utf8"
    database_charset: utf8mb4

    domain_name: https://domain.de/wallabag/web

    mailer_transport:  smtp
    mailer_user:       ~
    mailer_password:   ~
    mailer_host:       127.0.0.1
    mailer_port:       false
    mailer_encryption: ~
    mailer_auth_mode:  ~

    locale: de

    # A secret key that's used to generate certain security-related tokens
    secret: xxxx
    
    locale: en

    # two factor stuff
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_registration: false
    fosuser_confirmation: false

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: no-reply@wallabag.org

    rss_limit: 50
    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null

    # sentry logging
    sentry_dsn: ~
  ```
</details>

### What steps will reproduce the bug?
Loading / Reloading the Wallabag Webinterface / Site.
 
The bug:
The material-icons doesn't show up. 
E.g. in the article-preview from the greenish standard theme, on the bottom of each of the divs, near the date (or table-cells?): Only the "alternate Text" is showing and crumbling into one pile of unreadable text, without icons. 
I have read, that material-icons need to be included as Google-reference in the index.html, but i don't find any index.html in all of the wallabag directories.
..help..? please...?
