### ISSUE TITLE
500: Internal Server Error when I try to fetch a page

### ISSUE THREAD

**Issue by nikiie8** [wallabag/wallabag#5002]
Hi all
I faced with an error fetching a page https://www.gd.ru/articles/11674-prodvijenie-tovara-v-internete
It has JavaScript, so I used a trick with google bot user-agent.
The following configuration works pretty well in f43.me
```
title: //div[contains(@class, 'title')]
body: //div[@class='article-content']
http_header(User-Agent): Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
strip: //a[contains(@href, 'subscribe')]
```
But when I have decided to add this page to wallabag I faced with error 500. 
"500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, hashed_url, origin_url, given_url, hashed_given_url, .... SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xCC1\x0E\x830\x10...' for column `wallabag`.`wallabag_entry`.`headers` at row 1"

I have found that probably it happened due to utf8 in parameters.yml. But I have checked it and there I have utf8mb4.
I also checked wallabag database in MariaDB here I have the following results
```
+--------------------------+--------------------+
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8mb4            |
| character_set_connection | utf8mb4            |
| character_set_database   | utf8mb4            |
| character_set_filesystem | binary             |
| character_set_results    | utf8mb4            |
| character_set_server     | latin1             |
| character_set_system     | utf8               |
| collation_connection     | utf8mb4_general_ci |
| collation_database       | utf8mb4_general_ci |
| collation_server         | latin1_swedish_ci  |
+--------------------------+--------------------+

```
Could you please help.

-->
### Environment

* **Version**: Wallabag 2.4.1
* **Installation**: Git clone
* **PHP version**: 7.4.14
* **OS**: Debian 10
* **Database**: MariaDB 10.4.17
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabaguser
    database_password: 
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    server_name: 
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null

  ```
</details>
