### ISSUE TITLE
Automatic theme doesn't do anything

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/wallabag#5064]
### Environment

* **Version**: 2.4.1
* **Installation**: docker image `wallabag/wallabag:2.4.1`
* **PHP version**: PHP 7.3.25 (from `docker-compose exec wallabag php -v`)
* **OS**: Ubuntu 20.04 (hosting the docker container)
* **Database**: sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://mydomain.example.com'
    mailer_transport: smtp
    mailer_user: wb@example.com
    mailer_password: supersecretpassword
    mailer_host: smtp.example.com
    mailer_port: 587
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: supersecretvalue
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wb@example.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
    server_name: 'Your wallabag instance'
  ```
</details>

### What steps will reproduce the bug?

I expected "Automatic theme" to automatically switch between light and dark mode based on my device's settings (`prefers-color-scheme: dark/light`).

Currently when using Firefox on macOS 11.2.1 or Safari on iOS 14.4, the theme doesn't respect the OS choice.

I tried clicking on "Automatic theme" before and after changing the OS theme but it didn't do anything in both cases. I also tried switching WB to dark mode, and clicking on "Automatic theme" but it didn't do anything either.

I had no relevant message in the console.
