### ISSUE TITLE
Article containing multiple h1 is not saved properly (missing said h1's)

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/wallabag#5095]
### Environment

* **Version**: 2.4.1
* **Installation**: Official docker image
* **PHP version**: From official docker image
* **OS**: Docker running on Ubuntu 20.04
* **Database**: sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```yaml
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wb.example.com'
    mailer_transport: smtp
    mailer_user: wallabag@example.com
    mailer_password: password
    mailer_host: smtp.example.com
    mailer_port: 587
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: secret
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@example.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
    server_name: 'Your wallabag instance'
  ```
</details>

### What steps will reproduce the bug?

1. Add the following article : https://dafoster.net/articles/2021/02/16/building-web-apps-with-vue-and-django-the-ultimate-guide/
2. Notice that the `<h1>` tags inside the article are not saved in wallabag's DB, like "1 server or 2 servers?", or "1-server approach".
