### ISSUE TITLE
403 Forbidden /api through Wallabag Android App

### ISSUE THREAD

**Issue by cotsuka** [wallabag/wallabag#5181]
### Environment

* **Version**: 2.4.2
* **Installation**: https://aur.archlinux.org/packages/wallabag/
* **PHP version**: 7.4.16
* **OS**: Arch Linux
* **Database**: PostgreSQL 13.2
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: PASSWORDWASHERE
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.actualdomainwashere.com'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: SECRETWASHERE
    twofactor_auth: true
    twofactor_sender: no-reply@actualdomainwashere.com
    fosuser_registration: true
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@actualdomainwashere.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Running wallabag bare metal behind an nginx reverse proxy. When attempting to utilize the Android app, I'm receiving a 403 forbidden error during the initial connection test. It's interesting since I'm able to get a client ID and secret, but I'm seeing this in my logs:

```
ipaddresswashere - - [29/Mar/2021:11:41:15 -0700] "GET /api/entries/exists.json?url=wallabag-apiwrapper-test.example.com HTTP/2.0" 403 63 "-" "okhttp/4.9.0"
```

Result of `curl -I https://wallabag.actualdomainwashere.com`:

```
HTTP/2 302
server: nginx
content-type: text/html; charset=UTF-8
location: https://wallabag.actualdomainwashere.com/login
x-powered-by: PHP/7.4.16
set-cookie: PHPSESSID=vbt2o0lc5tiq7gjsg6nv9o6rj7; path=/; HttpOnly
cache-control: max-age=0, must-revalidate, private
date: Mon, 29 Mar 2021 18:46:35 GMT
expires: Mon, 29 Mar 2021 18:46:35 GMT
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block;
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'
strict-transport-security: max-age=31536000; includeSubDomains; preload
```

I can share the details of any of the include files from the nginx server block, but I've also attempted using the bone stock version in the documentation, which is still yielding the same results. It leads me to believe it's not an issue with my nginx setup. Notably, I can access the `/api/doc` endpoint when using the web UI perfectly fine.

```
server {
        server_name     wallabag.actualdomainwashere.com;
        set             $base /usr/share/webapps/wallabag/:/var/lib/wallabag;
        root            /srv/http/wallabag.actualdomainwashere.com/public/;

        # security
        include         /etc/nginx/security.conf;

        # logging
        access_log      /var/log/nginx/wallabag.actualdomainwashere.com.access.log;
        error_log       /var/log/nginx/wallabag.actualdomainwashere.com.error.log warn;

        # app.php fallback
        location / {
                try_files $uri /app.php?$is_args$args;
        }

        # additional config
        include /etc/nginx/general.conf;

        location ~ ^/app\.php(/|$) {
                fastcgi_pass    unix:/run/php-fpm7/php-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include /etc/nginx/php_fastcgi.conf;
                internal;
        }

        # return 404 for other php files
        location ~ \.php$ {
                return 404;
        }

    listen [::]:443 ssl http2; # managed by Certbot
    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wallabag.actualdomainwashere.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wallabag.actualdomainwashere.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    listen              80;
    listen              [::]:80;
    server_name         wallabag.actualdomainwashere.com;
    include             /etc/nginx/letsencrypt.conf;

    location / {
            return 301 https://wallabag.actualdomainwashere.com$request_uri;
    }
}
```
