### ISSUE TITLE
Geizhals.de breaks database serialization of headers

### ISSUE THREAD

**Issue by mweinelt** [wallabag/wallabag#5242]
### Environment

* **Version**: 2.4.1
* **Installation**: Selfhosted
* **PHP version**: 7.4.16
* **OS**: NixOS
* **Database**: PostgreSQL
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```yaml
  parameters:
    database_driver: pdo_pgsql
    database_host: /run/postgresql
    database_port: ~
    database_name: wallabag
    database_user: wallabag
    database_password: ~
    database_path: ~
    database_table_prefix: wallabag_
    database_socket: ~
    database_charset: utf8
    mailer_transport: smtp
    mailer_user: ~
    mailer_password: ~
    mailer_host: localhost
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    twofactor_auth: true
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    rss_limit: 50
    rabbitmq_host: ~
    rabbitmq_port: ~
    rabbitmq_user: ~
    rabbitmq_password: ~
    rabbitmq_prefetch_count: 10
    redis_scheme: unix
    redis_host: ~
    redis_port: ~
    redis_path: /run/redis/redis.sock
    redis_password: ~
    sentry_dsn: ~
  ```
</details>

### What steps will reproduce the bug?

Fetching the following page will reproducibly result in broken database value serialization for the header field in wallabag_entry.

https://geizhals.de/intellinet-6he-wandschrank-hellgrau-714150-a1724961.html?hloc=at&hloc=de

The serialization is broken in multiple ways:

1. The array length is at least 20
2. There is no closing bracket at the end

```
a:15:{s:4:"date";s:29:"Sun, 11 Apr 2021 14:40:22 GMT";s:12:"content-type";s:29:"text/html; charset=iso-8859-1";s:17:"transfer-encoding";s:7:"chunked";s:10:"connection";s:10:"keep-alive";s:15:"x-frame-options";s:4:"DENY";s:23:"content-security-policy";s:23:"frame-ancestors 'none';";s:7:"expires";s:29:"Thu, 08 Apr 2021 14:40:22 GMT";s:13:"cache-control";s:27:"no-cache, no-store, private";s:10:"set-cookie";s:221:"csrf=D879D950-9AD3-11EB-AC8B-E25602C1DF8D--bec497d9206230928150ce0d47c6481e4aaa88fa; path=/; secure; SameSite=Lax, GeizhalsConfcookie=hloc:default&atvate";s:10:"set-cookie";s:221:"csrf=D879D950-9AD3-11EB-AC8B-E25602C1DF8D--bec497d9206230928150ce0d47c6481e4aaa88fa; path=/; secure; SameSite=Lax, GeizhalsConfcookie=hloc:default&at
```

This in turn breaks the entries template like this

```
[2021-04-27 00:15:29] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 409 of 563 bytes'")." at /nix/store/jswygyiqy18h1b9llyw1fqh6w1l0nq7v-wallabag-2.4.1/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig line 57 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 409 of 563 bytes'\"). at /nix/store/jswygyiqy18h1b9llyw1fqh6w1l0nq7v-wallabag-2.4.1/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig:57, Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 409 of 563 bytes' at /nix/store/jswygyiqy18h1b9llyw1fqh6w1l0nq7v-wallabag-2.4.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:117)"} []
```

I can set the field to null (`N;`) and refetch the content to reproduce the issue.
