### ISSUE TITLE
API broken ? can't POST

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#5392]
### Environment

* **Version**: 2.4.2
* **Installation**: 
* **PHP version**: 7.4
* **OS**:ubuntu 20.04
* **Database**:mysql 8
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: walluser
    database_password: wallpass
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'http://wallabag:81/'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?
when running 
```
http POST http://wallabag:81/api/entries.json?access_token=YzE5MDVmMjQzYWQ5ZWQxN2U0MTQ2ZWU4MjE2ZDEzMmVkYjk5OWFkZjNlOGE5NGVmMzEwYjc5MjM2ZmJlZTBhMg\&url=https%3A%2F%2Ffoxmask.github.io%2Fpost%2F2021%2F07%2F28%2Fmonit-and-more%2F
```
got 
```
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, private
Connection: close
Content-Length: 57
Content-Type: application/json
Date: Thu, 12 Aug 2021 21:22:03 GMT
Server: Apache/2.4.41 (Ubuntu)

{
    "error": {
        "code": 500,
        "message": "Internal Server Error"
    }
}

``` 
and in var/log I get

```
[2021-08-12 23:19:17] request.INFO: Matched route "api_post_entries". {"route":"api_post_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::postEntriesAction","_format":"json","_route":"api_post_entries"},"request_uri":"http://wallabag:81/api/entries.json?access_token=YzE5MDVmMjQzYWQ5ZWQxN2U0MTQ2ZWU4MjE2ZDEzMmVkYjk5OWFkZjNlOGE5NGVmMzEwYjc5MjM2ZmJlZTBhMg&url=https%3A%2F%2Ffoxmask.github.io%2Fpost%2F2021%2F07%2F28%2Fmonit-and-more%2F","method":"POST"} []
[2021-08-12 23:19:17] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Wallabag\CoreBundle\Helper\UrlHasher::hashUrl() must be of the type string, null given, called in /home/foxmask/Projects/wallabag/src/Wallabag/CoreBundle/Repository/EntryRepository.php on line 367" at /home/foxmask/Projects/wallabag/src/Wallabag/CoreBundle/Helper/UrlHasher.php line 18 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Wallabag\\CoreBundle\\Helper\\UrlHasher::hashUrl() must be of the type string, null given, called in /home/foxmask/Projects/wallabag/src/Wallabag/CoreBundle/Repository/EntryRepository.php on line 367 at /home/foxmask/Projects/wallabag/src/Wallabag/CoreBundle/Helper/UrlHasher.php:18)"} []
```
