### ISSUE TITLE
Could not find any migrations to execute (PostgreSQL)

### ISSUE THREAD

**Issue by benneti** [wallabag/wallabag#5451]
### Environment

* **Version**:  2.4.2
* **Installation**: nix (see here for my config: https://git.tissot.de/benneti/nixos/src/branch/master/profiles/server/wallabag/default.nix )
* **PHP version**: 7.3
* **OS**: nixos
* **Database**: postgresql 11.3
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_socket: /run/postgresql/.s.PGSQL.5432
    database_name: wallabag
    database_user: wallabag
    database_table_prefix: wallabag_
    database_charset: utf8
    # not used but still needs to be set
    database_path: null
    database_host: null
    database_port: null
    database_password: null

    domain_name: https://wallabag.tissot.de
    server_name: "Wallabag"

    mailer_transport:  smtp
    # mailer_user:
    mailer_user:       ${email_user}
    mailer_password:   ${email_password}
    # mailer_user:       %env.email_user%
    # mailer_password:   %env.email_password%
    mailer_host:       smtp.strato.de
    mailer_port:       false
    mailer_encryption: ssl
    mailer_auth_mode:  login

    locale: en

    # A secret key that's used to generate certain security-related tokens
    # secret:  %env.wallabag_secret%
    secret:  ${wallabag_secret}

    # two factor stuff
    twofactor_auth: false
    # twofactor_sender: %env.email_user%
    twofactor_sender: ${email_user}

    # fosuser stuff
    fosuser_registration: true
    fosuser_confirmation: true

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    # from_email: %env.email_user%
    from_email:       ${email_user}

    rss_limit: 50

    # not used
    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null

    # sentry logging
    sentry_dsn: ~

  ```
</details>

### What steps will reproduce the bug?

running the installer fails due to missing migrations.
Initial database is empty and wallabag user can only access this database. Same issue also occurs when regenerating the database after granting the wallabag CREATEDB rights.

console wallabag:install --env=prod

```
wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------ -------- ----------------
  Checked                  Status   Recommendation
 ------------------------ -------- ----------------
  PDO Driver (pdo_pgsql)   OK!
  Database connection      OK!
  Database version         OK!
  curl_exec                OK!
  curl_multi_init          OK!
 ------------------------ -------- ----------------


 [OK] Success! Your system can run wallabag properly.


Step 2 of 4: Setting up database.
---------------------------------

 It appears that your database already exists. Would you like to reset it? (yes/no) [no]:
 > no

 Seems like your database contains schema. Do you want to reset it? (yes/no) [no]:
 > yes

 Dropping schema and creating schema...

In InstallCommand.php line 337:

  The command "doctrine:migrations:migrate" generates some errors:


                      Application Migrations


  Migrating up to 0 from 0
  19:49:54 ERROR     [console] Error thrown while running command "doctrine:migratio
  ns:migrate --no-interaction=1 --no-debug=1 --env=prod". Message: "Could not find a
  ny migrations to execute." ["exception" => Doctrine\DBAL\Migrations\MigrationExcep
  tion { …},"command" => "doctrine:migrations:migrate --no-interaction=1 --no-debug=
  1 --env=prod","message" => "Could not find any migrations to execute."]

  In MigrationException.php line 29:

    Could not find any migrations to execute.


  doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [
  --allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CO
  NFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|
  vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env
   ENV] [--no-debug] [--] <command> [<version>]


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```
