### ISSUE TITLE
Locally saved images not loading inside article with the `pixel_ratio` parameter

### ISSUE THREAD

**Issue by mmnaseri** [wallabag/wallabag#5464]
### Environment

* **Version**: 2.4.2
* **Installation**: Docker
* **PHP version**: bundled with Docker
* **OS**: Alpine
* **Database**: Postgres
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: postgres
    database_port: 5432
    database_name: [redacted]
    database_user: [redacted]
    database_password: [redacted]
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: [redacted]
    mailer_transport: [redacted]
    mailer_user: [redacted]
    mailer_password: [redacted]
    mailer_host: [redacted]
    mailer_port: [redacted]
    mailer_encryption: [redacted]
    mailer_auth_mode: [redacted]
    locale: en
    secret: [redacted]
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: [redacted]
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
    server_name: [redacted]
  ```
</details>

### What steps will reproduce the bug?

1. Add a new entry with some images.
2. Wait for the local fetch to be over.
3. Observe that the version displayed in the browser doesn't load the image.
4. Open the image in a new tab and remove the `pixel_ratio` URL parameter.
5. Observe that the image loads independently.
