### ISSUE TITLE
Migrating Wallabag from mysql to postgresql, missing relations error

### ISSUE THREAD

**Issue by solarchemist** [wallabag/wallabag#5502]
### Environment

* **Version**: 2.4.2
* **Installation**: git clone
* **PHP version**: 7.3.33
* **OS**: Ubuntu 20.04
* **Database**: MariaDB 10.4.22 on migration source, and PostgreSQL 14.1 on migration target.
* **pgloader**: 3.6.2 (installed from https://apt.postgresql.org/pub/repos/apt)
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> on the migration source (using MariaDB) is:</summary>

  ```
  parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: hunter2
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wlbg.mydomain.se'
    server_name: 'Wallabag on mydomain'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: supersecretstring
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: unix
    redis_host: localhost
    redis_port: null
    redis_path: /var/run/redis/redis-server.sock
    redis_password: null
    sentry_dsn: null
  ```
</details>

<details>
  <summary>My <code>app/config/parameters.yml</code> on the migration target (using PostgreSQL) is:</summary>

  ```
  parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: 5432
    database_name: wallabag
    database_user: taha
    database_password: hunter2
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wlbg.mydomain.se'
    server_name: 'Wallabag on mydomain'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: supersecretstring
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: unix
    redis_host: localhost
    redis_port: null
    redis_path: /var/run/redis/redis-server.sock
    redis_password: null
    sentry_dsn: null
  ```
</details>

In short, I wanted to see if I could migrate a Wallabag instance that uses MySQL to use PostgreSQL instead. This was motivated mainly by curiosity and a vague notion that PostgreSQL will be faster and/or easier to maintain.

Now, I am a total noob when it comes to SQL, so naturally I looked for some tool to perform the necessary "translation" 
from MySQL to PostgreSQL, and the best I found was [`pgloader`](https://github.com/dimitri/pgloader).

I performed this migration by writing an Ansible role that installs, updates and, as evident from this report, *attempts* to migrate Wallabag. The [Ansible role is published in full on Codeberg](https://codeberg.org/ansible/wallabag). 
I have kept track of my attempted migrations over the last few months in a (very verbose) [issue on that repo](https://codeberg.org/ansible/wallabag/issues/1), and I link to some specific comments in the text below instead of repeating the details here.

### What steps will reproduce the problem?

Assuming you have two fresh Ubuntu 20.04 instances, one with MariaDB (instance `A`) and one with PostgreSQL and pgloader (instance `B`).

1. Install Wallabag v2.4.2 on instance `A`. 
   Login and add some articles, and create some tags, stars, and public shares to the regular account.
2. Migrate the Wallabag database from mysql on `A` to postgresql on `B` using `pgloader` with default settings: 
  `pgloader mysql://wallabag:hunter2@localhost/wallabag postgresql:///wallabag` 
  (this works because we've first created an SSH port-forward from 3306 on instance `A` to `B`).
3. Install Wallabag v2.4.2 on instance `B` and configure it to use the postgresql database.
4. Enjoy Wallabag with our new database backend...?

Well, it almost works! I have observed only the following problems on the migrated instance:

+ **adding a new article fails**,
+ **tagging an article with a new tag fails**.

The error is the same in both cases, `internal server error 500`.
When trying to add a new article, the log shows
```
An exception occurred while executing 'SELECT NEXTVAL('"entry_id_seq"')': SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "entry_id_seq" does not exist LINE 1: SELECT NEXTVAL('"entry_id_seq"') ^
```
and when trying to tag an article with a not previously existing tag, the log shows
```
An exception occurred while executing 'SELECT NEXTVAL('"tag_id_seq"')': SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "tag_id_seq" does not exist LINE 1: SELECT NEXTVAL('"tag_id_seq"') ^
```

But other than that, all other operations I tested work, specifically:

+ tagging an article with a pre-existing tag works,
+ starring an existing article works, and so does unstarring,
+ editing an article title works,
+ marking an article as read works,
+ deleting an article works,
+ existing public links work.

I should mention that the `pgloader` migration completes [without any errors or warnings](https://codeberg.org/ansible/wallabag/issues/1#issuecomment-283113). That does not mean the problem cannot be due to `pgloader`, of course,
but I thought I should start by asking for help here, as I hope more experienced Wallabag users might perhaps recognise the error.

Also, if you are familiar with Ansible playbooks my role should make it quite easy to reproduce the migration.
In any case, my intention is to provide enough information in this issue so you won't have to.

### Missing *relations*?

Since this is a minimal Wallabag installation, with just one user and only a few articles added, I thought a visual inspection and comparison of the mysql and postgresql databases might reveal something.

So I loaded each of the databases into [Sequeler](https://github.com/Alecaddd/sequeler) and took a look around. Again, I have only poor familiarity with SQL, but as far as I could tell both databases contained exactly the same tables and the tables contained the same columns (with expected differences in some column datatypes, such as `int`, `bigint` and what not).

The only difference I could find was that the postgresql database was consistently missing any *relations*, whereas such relations existed for some tables in the mysql database (I took a screenshot, mysql above, postgresql below).

![relations missing in pgsql](https://nextcloud.chepec.se/s/Jkw6LCHW7FBzQdi/download)

### My attempt at a fix

Knowing that Wallabag requires us to perform certain [SQL operations on upgrade](https://doc.wallabag.org/en/admin/query-upgrade-23-24.html#postgresql), and since I noticed that some of those operations use the `REFERENCES` keyword, I thought, hey, let's run them, maybe that's what is missing.

So I identified all queries that contained `REFERENCES`, and ran them on the migrated postgresql database:

```
ALTER TABLE "wallabag_oauth2_access_tokens" ADD CONSTRAINT FK_368A4209A76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE "wallabag_oauth2_clients" ADD CONSTRAINT FK_635D765EA76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE "wallabag_oauth2_refresh_tokens" ADD CONSTRAINT FK_20C9FB24A76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE "wallabag_oauth2_auth_codes" ADD CONSTRAINT FK_EE52E3FAA76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE "wallabag_ignore_origin_user_rule" ADD CONSTRAINT fk_config FOREIGN KEY (config_id) REFERENCES "wallabag_config" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
```

But all I got was the error message `Cannot execute SQL ... constraint ... for relation ... already exists`.
Which surprised me, since it suggests the *relation* already exists. But if it does, why can't we see it in Sequeler? 

Which leaves me perplexed, and officially out of my depth. I hope your interest has been piqued, and feel free to ask me for further tests if you can think of any --- I have both Wallabag instances up and running for the time being, and I can easily nuke them and start over to test things.

Thanks for reading :-)
