### ISSUE TITLE
502 Bad Gateway on Android Client after successful Setup

### ISSUE THREAD

**Issue by nodu** [wallabag/wallabag#5509]
docker-compose.yml
```
version: '3'
services:
  wallabag:
    image: wallabag
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://removed
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    ports:
      - "8080:80"
    volumes:
      - /home/removed/wallabag/data/:/var/www/wallabag/data/
      - /home/removed/wallabag/images:/var/www/wallabag/web/assets/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
```
```
server {
        listen 443 ssl;
        server_name removed;

        ssl_certificate /etc/letsencrypt/removed.crt;
        ssl_certificate_key /etc/letsencrypt/removed.key;

	location / {
		proxy_pass http://192.168.0.6:8080;
		proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-For $remote_addr;
	}

}
```

### What steps will reproduce the bug?
														

```
➜  ~ (x) curl -I https://removed/
HTTP/1.1 302 Found
Server: nginx/1.21.4
Date: Tue, 14 Dec 2021 00:26:09 GMT
Content-Type: text/html; charset=UTF-8
Location: https://removed/login
Connection: keep-alive
Set-Cookie: PHPSESSID=asdf
; path=/; HttpOnly
Cache-Control: max-age=0, must-revalidate, private
pragma: no-cache
Expires: Tue, 14 Dec 2021 00:26:09 GMT
```
