### ISSUE TITLE
Issue with MOBI export

### ISSUE THREAD

**Issue by DavidJamesKent** [wallabag/wallabag#5514]
### Environment

* **Version**:  2.4.2
* **Installation**:  Followed the instructions at https://doc.wallabag.org/en/admin/installation/readme.html for a dedicated server
* **PHP version**:  7.4.25
* **OS**:  Debian 5.10.70-1 in an LXD container
* **Database**:  "mysql  Ver 15.1 Distrib 10.5.12-MariaDB"
* **Parameters**:  

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: [redacted]
    database_path: /var/lib/mysql/wallabag/
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: [redacted]
    server_name: [redacted]
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: [redacted]
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

The issue is that an exported MOBI file, when viewed in either Neoreader an on Onyx Boox device, or FBReader on Debian Linux, is missing chunks of text. The missing text *is* in the source MOBI file, so this seems to relate to how the file is rendered in those applications. The missing text is also visible when viewed in Wallbag, both in the Android app and in a browser.

In Android app: press and hold article; choose "Download as file." Select "MOBI." Open resulting MOBI file in eBook reader. The problem is apparent at least in the Neoreader app on an Onyx Boox Max Lumi.

On PC: Click article title. Click "Export" and select "MOBI." Open resulting MOBI file in eBook reader. The problem is apparent at least in FBReader 0.12.10 on Debian 5.15.0.

I've attached a screenshot of this issue manifesting [in this Financial Times article](https://www.ft.com/content/481d2685-733b-47fb-b74d-b452997b672e). The left side of the screenshot is the article rendered in FBReader. The right side is the MOBI file opened in Emacs. The original article says '"We need to understand how our **security can be ensured," he said. "So, without any funny business, we just put it** out there by saying that Nato shouldn't move any further east."' But it renders as '"We need to understand how our out there by saying that Nato shouldn't move any further east."' I have emphasized the portion that is elided. The exact same text is missing in the same article when viewed in Neoreader on the Onyx Boox device.

![2021-12-23-123718_1573x139_scrot](https://user-images.githubusercontent.com/50265987/147277053-f433c124-0765-4ce4-a53c-867288875ac9.png)
