### ISSUE TITLE
Unable to write in the "cache" directory

### ISSUE THREAD

**Issue by fculpo** [wallabag/wallabag#5520]
On a fresh instance of self hosted wallabag, I get this error related to cache directory

```
2022/01/01 19:20:46 [error] 262#262: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to write in the "cache" directory (/var/www/wallabag/var/cache/prod). in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel 

Stack trace: 
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()                                                                                                                             
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\Kernel->boot()                                                                                                                                          
#3 /var/www/wallabag/web/app.php(13): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
```

**Comment by fculpo** [comment]
I'm simply using docker image wallabag/wallabag

**Comment by yitsushi** [comment]
Same error here using `wallabag/wallabag:2.4.3`, details may help.

Docker compose file (docker stack deploy):

```yaml
---
version: '3.2'

services:
  web:
    image: wallabag/wallabag:2.4.3
    networks:
      - traefik-public
    ports:
      - 80
    environment:
      - POSTGRES_PASSWORD="xxx"
      - POSTGRES_USER="wallabag"
      - SYMFONY__ENV__DATABASE_DRIVER="pdo_pgsql"
      - SYMFONY__ENV__DATABASE_HOST="xxx"
      - SYMFONY__ENV__DATABASE_PORT="5432"
      - SYMFONY__ENV__DATABASE_NAME="wallabag"
      - SYMFONY__ENV__DATABASE_USER="wallabag"
      - SYMFONY__ENV__REDIS_PASSWORD="xxx"
      - SYMFONY__ENV__SECRET="xxx"
      - SYMFONY__ENV__MAILER_HOST="xxx"
      - SYMFONY__ENV__MAILER_USER="xxx"
      - SYMFONY__ENV__MAILER_PASSWORD="xxx"
      - SYMFONY__ENV__FROM_EMAIL="xxx"
      - SYMFONY__ENV__TWOFACTOR_AUTH="true"
      - SYMFONY__ENV__TWOFACTOR_SENDER="xxx"
      - SYMFONY__ENV__FOSUSER_REGISTRATION="false"
      - SYMFONY__ENV__FOSUSER_CONFIRMATION="false"
      - SYMFONY__ENV__DOMAIN_NAME="xxx"
      - SYMFONY__ENV__SERVER_NAME="xxx"
      - SYMFONY__ENV__REDIS_HOST="xxx"
      - SYMFONY__ENV__REDIS_PORT="6379"
      - SYMFONY__ENV__DATABASE_PASSWORD="xxx"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wallabag-router.rule=Host(`xxx`)"
        - "traefik.http.services.wallabag-service.loadbalancer.server.port=80"
        - "traefik.http.routers.wallabag-router.tls=true"
        - "traefik.http.routers.wallabag-router.tls.certresolver=cloudflare"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
```

Error Message:

```
2022/02/15 09:56:13 [error] 217#217: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to write in the "cache" directory (/var/www/wallabag/var/cache/prod). in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:768
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/web/app.php(13): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 768" while reading response header from upstream, client: 10.0.4.7, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"
```

Directory permissions:
```
$ docker exec -it wallabag_web.1.9xe38yco9fs9yfwwj7tlxuca8 /bin/ash
/ # ls -la /var/www/wallabag/var/
total 108
drwxr-xr-x    1 nobody   nobody        4096 Feb 15 09:53 .
drwxr-xr-x    1 nobody   nobody        4096 Feb 14 18:56 ..
-rw-r--r--    1 nobody   nobody       33831 Feb 14 18:57 SymfonyRequirements.php
-rw-r--r--    1 root     root         42982 Feb 15 09:53 bootstrap.php.cache
drwxr-xr-x    3 root     root          4096 Feb 15 09:53 cache
drwxr-xr-x    1 nobody   nobody        4096 Feb 14 18:56 logs
drwxr-xr-x    1 nobody   nobody        4096 Feb 14 18:56 sessions
/ # ls -la /var/www/wallabag/var/cache/
total 16
drwxr-xr-x    3 root     root          4096 Feb 15 09:53 .
drwxr-xr-x    1 nobody   nobody        4096 Feb 15 09:53 ..
drwxr-xr-x    2 root     root          4096 Feb 15 09:53 prod
/ # ls -la /var/www/wallabag/var/cache/prod/
total 8
drwxr-xr-x    2 root     root          4096 Feb 15 09:53 .
drwxr-xr-x    3 root     root          4096 Feb 15 09:53 ..
```
