### ISSUE TITLE
502 when trying to import a specific article

### ISSUE THREAD

**Issue by kolaente** [wallabag/wallabag#5558]
### Environment

* **Version**: 2.4.2
* **Installation**: Official Docker image `wallabag/wallabag`
* **PHP version**:
* **OS**:
* **Database**: mariadb 10
* **Parameters**:

I don't have a parameters.yml file.

Here's my docker compose config:

```yaml
version: '2'

services:
  web:
    image: wallabag/wallabag
    environment:
      MYSQL_ROOT_PASSWORD: notthepassword
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: db
      SYMFONY__ENV__DATABASE_PORT: '3306'
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__DATABASE_PASSWORD: notthepassword
      SYMFONY__ENV__MAILER_HOST: mail.kolaente.de
      SYMFONY__ENV__MAILER_USER: wallabag@domain
      SYMFONY__ENV__MAILER_PASSWORD: notthepassword
      SYMFONY__ENV__FROM_EMAIL: wallabag@domain
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.domain
    volumes:
      - /var/apps/wallabag/images:/var/www/wallabag/web/assets/images
    networks:
      - default
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.domain`)"
      - "traefik.http.routers.wallabag.entrypoints=https"
      - "traefik.http.routers.wallabag.tls.certResolver=basic"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: notthepassword
      MYSQL_USER: wallabag
      MYSQL_USER_PASSWORD: notthepassword
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/apps/wallabag/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      default:
      backup:
        aliases:
          - wallabag-db

networks:
  web:
    external: true
  backup:
    external: true
```

### What steps will reproduce the bug?

Trying to archive [this url](https://hubermanlab.com/toolkit-for-sleep/) (other urls work fine, as far as I can tell) will always crash wallabag with this error in the docker logs:

```
db_1   | 2022-01-14 16:50:39 12 [Warning] Aborted connection 12 to db: 'wallabag' user: 'wallabag' host: '192.168.144.3' (Got an error reading communication packets)
web_1  | 2022/01/14 16:50:39 [error] 284#284: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.192.7, server: _, request: "POST /new-entry HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.domain", referrer: "https://wallabag.domain/"
web_1  | 192.168.192.7 - - [14/Jan/2022:16:50:39 +0000] "POST /new-entry HTTP/1.1" 502 150 "https://wallabag.domain/" "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
```

I assume this is an issue somewhere in the php stack, likely with encoding. I've only seen these particular errors in other contexts where the fpm worker handling the request died because of a memory corruption or similar - pretty edge-case.
