### ISSUE TITLE
Wrong number of entries for tag feeds

### ISSUE THREAD

**Issue by christianjunk** [wallabag/wallabag#5584]
### Environment

* **Version**:
* **Installation**:
* **PHP version**:
* **OS**:
* **Database**:
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
 parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password:
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 
    server_name: "Private wallabag instance"
    mailer_transport: smtp
    mailer_user: apikey
    mailer_password: 
    mailer_host: 
    mailer_port: 
    mailer_encryption: 
    mailer_auth_mode:
    locale: de
    secret:
    twofactor_auth: 
    twofactor_sender:
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: 
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Since version 2.3.0 the feature of [RSS for tags](https://github.com/wallabag/wallabag/pull/3207) was added. But the current code ignores the `wallabag_core.feed_limit`. Instead the `items_per_page` setting will be used for the tag feeds.

In my opinion this needs to be fixed, because the first setting is controlling the feeds, latter controls the entries in the web interface.
