### ISSUE TITLE
Can't import over the web interface with PHP 8.1

### ISSUE THREAD

**Issue by dertuxmalwieder** [wallabag/wallabag#5631]
### Environment

* **Version**: 6f5298a2f5642d445e7e92e651d464c8fc9f2a38
* **Installation**: git clone
* **PHP version**: 8.1.3
* **OS**: Linux
* **Database**: MariaDB 10.3.22
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: REDACTED_wallabag
    database_user: REDACTED
    database_password: REDACTED
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: REDACTED
    server_name: REDACTED
    mailer_transport: smtp
    mailer_user: wallabag
    mailer_password: REDACTED
    mailer_host: 127.0.0.1
    mailer_port: 587
    mailer_encryption: null
    mailer_auth_mode: null
    locale: de
    secret: REDACTED
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 200
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

1. Create a CSV file from Instapaper.
2. Try to import that CSV file.

### Expected behavior:

Import works.

### Actual outcome:

Symfony throws an error:

    This form should not contain extra fields.

This happens with both a modified Vivaldi and a clean Firefox installation. Importing per `bin/console` works, so the file is not the issue.
