### ISSUE TITLE
Invalid credential at first login

### ISSUE THREAD

**Issue by MattRGX** [wallabag/wallabag#5645]
### Environment

* **Version**: 2.4.3
* **Installation**: ???
* **PHP version**: 8.1
* **OS**: Debian 11
* **Database**: Postgresql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: 192.168.1.2
    database_port: 5432
    database_name: wallabag_db
    database_user: wallabag
    database_password: ***************************************
    database_path: null
    database_table_prefix: wb_
    database_socket: null
    database_charset: utf8
    domain_name: http://192.168.1.2/wallabag/web
    server_name: mywallabag
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: ******************************
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

Hello,

i've just installed wallabag on my home server (self hosted) and when trying to login for the first time, i got an error message that says that my credentials are invalid. I'm pretty sure about the value of user and password. 
Any help to get me login in ? 

(i've asked for help on the gitter channel since a week now and didn't get any help, that's why i ask here)

Thanks a lot for your help !

Matthieu
