### ISSUE TITLE
Attempted to call an undefined method when using browser extension or android app

### ISSUE THREAD

**Issue by landowark** [wallabag/wallabag#5657]
### Environment

* **Version**: 2.4.3
* **Installation**: git clone
* **PHP version**: 7.3
* **OS**: raspbian 64 bit
* **Database**: mariadb
* **Parameters**: below

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabaguser
    database_password: <password>
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://<url>'
    server_name: 'https://<url>'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Upon using the chrome extension or trying to access articles or share to the android app I get hit with server failures (error 500 on the android app). The browser extension will result in a clipped web page, but the android app fails completely.
Upon checking the prod.log I see:

```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getAttributes" of class "ReflectionClass"." at /var/www/wallabag/vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php line 26 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getAttributes\" of class \"ReflectionClass\". at /var/www/wallabag/vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php:26)"} []
```
I'm wondering if maybe there's a missing php dependency somewhere.
