### ISSUE TITLE
No style, no CSS on homepage

### ISSUE THREAD

**Issue by MattRGX** [wallabag/wallabag#5718]
### Environment

* **Version**: 2.4.3
* **Installation**: Manual
* **PHP version**: 8.1
* **OS**: Debian 11
* **Database**: Postgresql

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  # This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_host: ****
    database_port: 5432
    database_name: ****
    database_user: ****
    database_password: *****
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: https://debian-serveur-matt.lan/wallabag
    server_name: MattWallabag
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: ******
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```
</details>

Hello everyone 

First of all thanks for your work.

My wallabag instance doesn't have any CSS or style loaded
![image](https://user-images.githubusercontent.com/58740578/162229533-83c4ce45-7bf1-4777-945b-eb24bc2949c0.png)

my wallabag installation is manual.

i don't know where to start looking for to make my wallabag looks nice ?
Thanks for your help.
