### ISSUE TITLE
Export ePub : Call to a member function addIndexPoint() on boolean

### ISSUE THREAD

**Issue by WhilelM** [wallabag/wallabag#5731]
Database:     The storage system your instance is using (SQLite, MySQL/MariaDB or PostgreSQL) with the version
Parameters:   Paste the content of your app/config/parameters.yml (hide sensitive stuff if you want)
-->
### Environment

* **Version**: 2.4.3
* **Installation**: 
* **PHP version**:php 7.3
* **OS**: debian 10.12
* **Database**: mariadb-server-10.3
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: accru_wallabag
    database_user: accru_wallabag
    database_password: X
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: X
    server_name: X
    mailer_transport: smtp
    mailer_user: X
    mailer_password: X
    mailer_host: X
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: X
    twofactor_auth: false
    twofactor_sender: X
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: X
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```
</details>

### What steps will reproduce the bug?

When i try to export ePub from flitered list unread articles (with one or multiple articles), i get after ~20s a "500 Internal error : Call to a member function addIndexPoint() on boolean". If I try to export from displayed page article, it works.
