### ISSUE TITLE
Every other http request fails with status 000

### ISSUE THREAD

**Issue by JoshuaCrewe** [wallabag/wallabag#5780]
### Environment

* **Version**:  2.4.3
* **Installation**:  Docker (I am running on armv7 so actually using https://hub.docker.com/r/leolivier/wallabag )
* **PHP version**: 7.3.33
* **OS**: Arch Linux Arm
* **Database**: Ver 15.1 Distrib 10.5.15-MariaDB
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: pocket_db
    database_port: 3306
    database_name: pocket
    database_user: root
    database_password: Licorice-Retrain-Juncture8
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.domain.co.uk:443'
    server_name: Pocket
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: xxxxxxxxxxxxxxxxxxxxxxxxx
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: address@domain.co.uk
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: xxxxxxxx
    rabbitmq_password: xxxxxxxx
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

I am experiencing a weird scenario. It all used to work and has worked for a month or so, since updating the docker container every other request fails. Visually it looks like the styles and scripts are not being loaded. I have `SYMFONY__ENV__DOMAIN_NAME` set correctly and I cleared the cache and made sure the database was migrated correctly.

A failed request in nginx-proxy looks like this : 
```
2022/05/04 08:35:55 [error] 208#208: *548 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 192.168.1.1, server: wallabag.domain.co.uk, request: "HEAD /wallassets/material.js HTTP/2.0", upstream: "http://172.22.0.6:3306/wallassets/material.js", host: "wallabag.domain.co.uk"
```

A successful request looks like this :

```
nginx.1     | wallabag.domain.co.uk 192.168.1.1 - - [04/May/2022:08:35:55 +0000] "HEAD /wallassets/material.js HTTP/2.0" 009 0 "-" "curl/7.83.0" "172.22.0.6:3306"
```
What is strange is that it looks like it is trying to make an HTTP request to the database server.

This isn't a new install and has worked fine, I am hosting other things on the same system with nginx-proxy which doesn't seem to have this problem. It is possible that there is something wrong with the Docker image (which I got from https://github.com/wallabag/wallabag/issues/4872#issuecomment-753950794 ) but I didn't think this was doing anything fancy. If @leolivier is reading this, perhaps they can help? A fresh install doesn't help either.

Please feel free to close this issue if it is too far outside of what Wallabag has control over (i.e. the docker setup). Would love to know what is going on though!

**Comment by JoshuaCrewe** [comment]
I was made aware of this issue https://github.com/wallabag/docker/issues/266#issuecomment-897066878 which shows that you can use the docker image on a raspberry pi. I updated my docker compose to match the issue and it appeared to build. 

The end result is the same though.

**Comment by leolivier** [comment]
Hi @JoshuaCrewe 
I indeed have an automated build of wallabag each first day of the month and then update the docker hub image. I just tested the new image on my own raspberry pi and everything looks fine so I don't think it's related to the image itself...

**Comment by JoshuaCrewe** [comment]
@leolivier thanks for chiming in, thats really helpful. This has been a bit of a head scratcher for sure, I am not sure what has changed or at what point in the stack to investigate next.

**Comment by leolivier** [comment]
Well, actually I'm facing issues from time to time after updates but usually a simple full `docker-compose down` followed by `docker-compose up -d` fixes the issue.

**Comment by JoshuaCrewe** [comment]
On this occasion I am getting the same experience with your docker image but also with one built right from the git repo I think. It is hard to tell how much is just being cached along the network though.

I have definitely done and up and down a bunch of times though which doesn't fix the issue. I suppose that there is going to be a simple cause at the end of it though.

**Comment by JoshuaCrewe** [comment]
@leolivier do you use nginx-proxy as well? Do you use a docker-compose file which looks the same as the one in the repo here?

**Comment by leolivier** [comment]
@JoshuaCrewe I'm using an Apache2 reverse proxy.
My docker-compose is like this:
```
version: '3'
services:
  wallabag:
    container_name: wallabag
    image: leolivier/wallabag:armv7-rpi
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=xxx
      - SYMFONY__ENV__DATABASE_PASSWORD=xxxx
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__SECRET=xxx
      - SYMFONY__ENV__LOCALE=fr_FR
      - SYMFONY__ENV__MAILER_HOST=xxx
      - SYMFONY__ENV__MAILER_USER=xxx
      - SYMFONY__ENV__MAILER_PASSWORD=xxx
      - SYMFONY__ENV__FROM_EMAIL=xxx
      - SYMFONY__ENV__DOMAIN_NAME=xxx
    ports:
      - "192.168.1.8:11080:80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    restart: always
  db:
    container_name: wallabag.db
    image: linuxserver/mariadb:alpine
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - PGID=1000
      - PUID=1000
    volumes:
      - ./data:/config
    restart: unless-stopped
    ports:
      - 3306:3306
```
