### ISSUE TITLE
[RuntimeException] require.composer is invalid

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#5811]
### Environment

* **Version**: 2.4.3 trying to update to 2.5.0
* **Installation**: Git
* **PHP version**: 7.4.3
* **OS**: Ubuntu 20.04 (recent patchlevel)
* **Database**: MariaDB
* **Parameters**: "make update"

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: xxx
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: xxx
    twofactor_auth: false
    twofactor_sender: wallabag@deimeke.ruhr
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: wallabag@deimeke.ruhr
    rss_limit: 500
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    domain_name: 'https://wallabag.deimeke.ruhr'
    server_name: wallabag.deimeke.ruhr
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

`make update` reproduces the bug.

```
$ sudo -u www-data make update
remote: Enumerating objects: 1897, done.
remote: Counting objects: 100% (916/916), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 1897 (delta 775), reused 900 (delta 767), pack-reused 981
Receiving objects: 100% (1897/1897), 13.91 MiB | 12.91 MiB/s, done.
Resolving deltas: 100% (1091/1091), completed with 155 local objects.
From https://github.com/wallabag/wallabag
 * [new branch]          2.6.0        -> origin/2.6.0
   6f5298a2f..84c026081  master       -> origin/master
 * [new branch]          poc-v3       -> origin/poc-v3
 + 694beb42c...357f9cc7e remove-baggy -> origin/remove-baggy  (forced update)
 * [new tag]             2.5.0        -> 2.5.0
Previous HEAD position was 6f5298a2f Merge pull request #5619 from wallabag/prepare-2.4.3
HEAD is now at 84c026081 Merge pull request #5799 from wallabag/release/2.5.0

                                                                                         
  [RuntimeException]                                                                     
  require.composer is invalid, it should have a vendor name, a forward slash, and a pac  
  kage name. The vendor and package name can be words separated by -, . or _. The compl  
  ete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*  
  $".                                                                                    
                                                                                         

make: *** [GNUmakefile:24: update] Error 1
```
