### ISSUE TITLE
"require.composer is invalid" when upgrading to 2.5.0

### ISSUE THREAD

**Issue by meepmeep** [wallabag/wallabag#5823]
### Environment

* **Version**: Trying to update to 2.5.0 
* **Installation**: git
* **PHP version**: 7.4
* **OS**: Debian 11.3
* **Database**: Mysql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: XYZ
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://mydomain.tld'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: XYZ
    twofactor_auth: true
    twofactor_sender: no-reply@mydomain.tld
    fosuser_registration: false
    fosuser_confirmation: true
    from_email: no-reply@mydomain.tld
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    server_name: 'Wallabag !'

  ```
</details>

### What steps will reproduce the bug?

I was on 2.4.3, trying to update to 2.5.0 with a simple `make update`. I got this error message, but wallabag seems to be correctly update to 2.5.0
```
In RootPackageLoader.php line 147:

  require.composer is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([
  _.]?|-{0,2})[a-z0-9]+)*$".


make: *** [GNUmakefile:24: update] Error 1
```
