### ISSUE TITLE
500 error due to missing twig template when 2FA is enabled after having upgraded to docker image 2.5.0

### ISSUE THREAD

**Issue by brouberol** [wallabag/wallabag#5824]
### Environment

* **Version**: `2.5.0`
* **Installation**: installed via the official docker image
* **PHP version**: `PHP 7.4.29 (cli) (built: Apr 23 2022 07:09:26) ( NTS )`
* **OS**: Running in docker, OS kernel `Linux 69fc8d98f3db 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 Linux`
* **Database**: `sqlite`
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: '[REDACTED]
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: [REDACTED]
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@example.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

I have 2FA enabled on my self-hosted wallabag instance, running via docker. I was happily running wallabag 2.4.3 and I upgraded the image tag to `2.5.0`. Requesting the wallabag main page redirects me to the `/2fa` page and displays the following error message

```

500: Internal Server Error

Unable to find template "WallabagUserBundle::layout.html.twig|material" in "WallabagUserBundle:Authentication:form.html.twig" at line 2.
```

See attached screenshot:
<img width="449" alt="Screenshot 2022-05-23 at 13 36 01" src="https://user-images.githubusercontent.com/480131/169810813-b43fa2b4-77d1-4cf4-a4d6-6fcffc5fc1e0.png">

Rolling back to the `2.4.3` docker image tag allows me to get back to a working state.

Thanks!
