### ISSUE TITLE
apiwrapper error 500 on mobile app

### ISSUE THREAD

**Issue by meepmeep** [wallabag/wallabag#5852]
### Environment

* **Version**: 2.5.1
* **Installation**: git clone
* **PHP version**:  7.4
* **OS**: Debian 11
* **Database**: Mysql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: XXXX
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://mydomain.tld
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: XXXX
    twofactor_auth: true
    twofactor_sender: no-reply@mydomain.tld
    fosuser_registration: false
    fosuser_confirmation: true
    from_email: no-reply@mydomain.tld
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    server_name: 'Wallabag !'

  ```
</details>

### What steps will reproduce the bug?

Everytimes I start the mobile app or try to synchronise my data, I get this error message (from the notification center).
On the website, everything is working fine.

`Erreur serveur
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Pile d'erreur :
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
 at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
 at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
 at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
 at wallabag.apiwrapper.WallabagService.getTags(WallabagService.java:1037)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.initTagMapsFromServer(ArticleUpdater.java:216)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:161)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
 at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
 at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
 at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
 at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
 at java.lang.Thread.run(Thread.java:923)`
