### ISSUE TITLE
Unable to activate user with /bin/console

### ISSUE THREAD

**Issue by Entmatix** [wallabag/wallabag#5870]
### Environment

* **Version**: docker latest (2.5.1)
* **Installation**: docker image
* **PHP version**:
* **OS**: Slackware 15.0
* **Database**: default (sqlite)
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://mydomain.com'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: ...
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@example.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

docker compose file:
```
services:
  app:
    image: wallabag/wallabag:latest
    restart: always
    # network_mode: host
    ports:
      - "50081:80"
    volumes:
      - /mnt/media/docker/containers/wallabag/data:/var/www/wallabag/data
      - /mnt/media/docker/containers/wallabag/images:/var/www/wallabag/web/assets/images
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://mydomain.com

networks:
  default:
    name: dockerpub0
```

Steps:
1. Run `docker compose up -d`.
2. Open web page of self-hosted wallabag.
3. Click on Register.
4. Enter credentials (user - username).
5. Click Register.
6. Open terminal.
7. `docker exec -it wallabag-app-1 sh`
8. `cd /var/www/wallabag`
9. According to https://doc.wallabag.org/en/admin/console_commands.html
```
./bin/console fos:user:activate username

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:52
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(27): Symfony\Component\Conso in /var/www/wallabag/app/AppKernel.php on line 52
```
