### ISSUE TITLE
upgrade dies midway and renders wallabag unusable if php < 7.4.1

### ISSUE THREAD

**Issue by hobbes** [wallabag/wallabag#5886]
### Environment

* **Version**: 2.5.1
* **Installation**: git clone
* **PHP version**: 7.3.29-1~deb10u1
* **OS**: debian buster
* **Database**: postgresql 11.12-0+deb10u1
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  # This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: hidden
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.example.net'
    mailer_transport: null
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 'hidden'
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    server_name: Wallabag@example
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

I launched the update command (make update),
it complained about composer being too old, so I installed composer 2.2 in the wallabag directory,
it went further, downloaded a bunch of requirements, started to install, then 

Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.1". You are running 7.3.29-1~deb10u1.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.1". You are running 7.3.29-1~deb10u1. in /home/poukram/wallabag/vendor/composer/platform_check.php on line 24
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception

                                                         
  [RuntimeException]                                     
  An error occurred when generating the bootstrap file.  
                                                         

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

make: *** [GNUmakefile:24: update] Error 1

Now my wallabag is half updated, so it won't run anymore...

I understand the deprecation of old versions, and it was noted in the 2.5.0 release notes (I only read the 2.5.1...) but shouldn't it be checked *before* starting the upgrade ?
