### ISSUE TITLE
How to modify php-fpm run path?

### ISSUE THREAD

**Issue by everydayrain** [wallabag/wallabag#5927]
### Environment

* **Version**: Not sure, can't make it to WUI; based of git clone https://github.com/wallabag/wallabag.git
* **Installation**: git clone https://github.com/wallabag/wallabag.git
* **PHP version**: 7.4
* **OS**: Debian 11
* **Database**: MariaDB 15.1
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: [mymariadbuser]
    database_password: [mymariadbpasswd]
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: '[mydomainname]'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: [thesecretImade]
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: 
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?
Recently rebuilt my Raspberry Pi OS, installed Wallabag today.  The install runs fine without errors.  When I head to the WUI I receive an Apache 503 error.  Digging around a bit, I noticed that somewhere Wallabag is trying to use the path /run/php/7.0-fpm.sock, when my version is 7.4.  Not sure if that is the root of my problems, but its a start.  Where can I correct that path? 

This is the log content:

$ tail /var/log/apache2/wallabag_error.log
[Sat Aug 13 09:06:14.143127 2022] [proxy:error] [pid 12374] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.0-fpm.sock (localhost:8000) failed
[Sat Aug 13 09:06:14.143460 2022] [proxy_fcgi:error] [pid 12374] [client 192.168.1.1:51954] AH01079: failed to make connection to backend: httpd-UDS
