### ISSUE TITLE
Error FastCGI Allowed memory size

### ISSUE THREAD

**Issue by JuanRodenas** [wallabag/wallabag#6101]
Thank you for reporting an issue.

Please fill in as much of the template below as you're able.

Version: 2.5.2
Installation: Docker
PHP version:  7
OS: Linux Ubuntu server 20.04
Database:  SQLite

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: 
    database_user: 
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 
    server_name: 
    mailer_transport: 
    mailer_user: 
    mailer_password: 
    mailer_host: 
    mailer_port: 
    mailer_encryption: 
    mailer_auth_mode: 
    locale: en
    secret: 
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: 
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: wgredis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```
</details>

### What steps will reproduce the bug?

Hello, when importing the pocket markers, 2 errors are reproduced:
* The first one is nginx problem, fastcgi, I had to increase the response time:
```bash
wallabag  | 2022/11/26 10:07:53 [error] 254#254: *4 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.10.2.6, server: _, request: "GET /import/pocket/callback HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
```

Fixed with:
```
fastcgi_read_timeout 600;
fastcgi_send_timeout 600;
fastcgi_connect_timeout 600;
```

* The second error after this one, happens with the php memory limit value. fixed loading my own `php.ini` and increased the `memory_limit = 512M`.
```bash
wallabag  | 2022/11/26 10:11:53 [error] 254#254: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1142784 bytes) in /var/www/wallabag/vendor/j0k3r/graby/src/Graby.php on line 332" while reading response header from upstream, client: 10.10.2.6, server: _, request: "GET /import/pocket/callback HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"
```

Is there any workaround to be able to load the pocket bookmarks?.
