### ISSUE TITLE
Wallabag fresh install nothing shows up (blank white page).

### ISSUE THREAD

**Issue by apoorv569** [wallabag/wallabag#6126]
**Describe what's wrong:**
I recently installed `wallabag` on my `Proxmox` server in a `unprivileged LXC` container, I copied the `docker-compose` file from here https://github.com/wallabag/docker#docker-compose.

 At first I was having problems with the database, I was getting errors saying `Access denied for user root@localhost`, so I swapped out the `mariadb` image in the `docker-compose` file to `linuxserver`'s `mariadb` image and it worked.

But now when I open the URL/IP to the server in the browser I just get a blank white page nothing else.

The `docker-compose logs -f` gives me this error,
```shell
wallabag_1  | 10.10.10.154 - - [06/Dec/2022:09:51:27 +0000] "POST /oauth/v2/token HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; rv:107.0) Gecko/20100101 Firefox/107.0"
wallabag_1  | 2022/12/06 09:51:27 [error] 180#180: *85 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_oauth2_clients in
/var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
wallabag_1  | Stack trace:
wallabag_1  | #0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(82): PDO->prepare('SELECT t0.rando...', Array)
wallabag_1  | #1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1301): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.rando...')
wallabag_1  | #2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.rando...', Array, Array)
wallabag_1  | #3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
wallabag_1  | #4 /var/www/wallabag/src/Wallabag/ApiBundle/Repository/ClientRepository.php(17): Doctrine\ORM\EntityRepository->findOneBy(Array, NULL)
wallabag_1  | #5" while reading response header from upstream, client: 10.10.10.154, server: _, request: "POST /oauth/v2/token HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "MYDOMAIN.COM"
wallabag_1  | 127.0.0.1 - - [06/Dec/2022:09:51:57 +0000] "GET / HTTP/1.1" 499 0 "-" "Wget"
wallabag_1  | 127.0.0.1 - - [06/Dec/2022:09:53:00 +0000] "GET / HTTP/1.1" 499 0 "-" "Wget"
```

Here is my entire `docker-compose.yml` file,
```yaml
version: '3'
services:

  wallabag:
    image: wallabag/wallabag:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${DB_PASS}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME="MYDOMAIN.COM"
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    ports:
      - 80:80
    volumes:
      - ./appdata/wallabag/config/:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - TZ=MY_TIMEZONE
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=wallabag
      - MYSQL_USER=wallabag
    volumes:
      - ./appdata/wallabag/db/:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    restart: unless-stopped
```
