### ISSUE TITLE
.github/CONTRIBUTING.md doesn't work

### ISSUE THREAD

**Issue by caspermeijn** [wallabag/wallabag#6173]
### Environment

* **Version**: master (c684ad2d)
* **Installation**: Using .github/CONTRIBUTING.md Docker instructions
* **PHP version**: 
* **OS**: Ubuntu
* **Database**: sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_sqlite
    database_driver_class: ~
    database_host: 127.0.0.1
    database_port: ~
    database_name: symfony
    database_user: root
    database_password: ~
    database_path: %kernel.project_dir%/data/db/wallabag.sqlite
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8

    domain_name: http://localhost:8000
    server_name: "Your wallabag instance"

    mailer_transport:  smtp
    mailer_user:       ~
    mailer_password:   ~
    mailer_host:       127.0.0.1
    mailer_port:       25
    mailer_encryption: ~
    mailer_auth_mode:  ~

    locale:            en

    # A secret key that's used to generate certain security-related tokens
    secret: ch4n63m31fy0uc4n

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_registration: true
    fosuser_confirmation: true

    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: wallabag@example.com

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: ~
    redis_password: ~

    # Sentry
    sentry_dsn: ~

    session_handler: ~

  ```
</details>

### What steps will reproduce the bug?

Executing .github/CONTRIBUTING.md Docker instructions result in a exception, which causes the installation to be aborted:
```
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-cmd event terminated with an exception

                                                                                                    
  [Symfony\Component\Yaml\Exception\ParseException]                                                 
  The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 9 (  
  near "database_path: %kernel.project_dir%/data/db/wallabag.sqlite").                              
                                                                                                    
```

It seems that `database_path` in parameters.yml is not correctly escaped. I was not able to find how this line is created.

### Second issue
When the `database_path` is fixed, the composer install step will ask for:
```
Some parameters are missing. Please provide them.
mailer_dsn ('smtp://127.0.0.1'): 
```
I think this should have a default value.
