### ISSUE TITLE
`Uncaught PHP Exception InvalidArgumentException: "Unable to parse URI: //:0"` blocks Android sync

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#6186]
### Environment

* **Version**: 2.5.1
* **Installation**: OpenBSD package based on a git clone https://scm.example.net/git/openbsd-ports/tree/www/wallabag
* **PHP version**: 8.0.26
* **OS**: OpenBSD
* **Database**: MySQL
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is a "template" of what your parameters.yml file should look like
parameters:
    # Uncomment these settings or manually update your parameters.yml
    # to use docker-compose
    #
    # database_driver: %env.database_driver%
    # database_host: %env.database_host%
    # database_port: %env.database_port%
    # database_name: %env.database_name%
    # database_user: %env.database_user%
    # database_password: %env.database_password%

    database_driver: pdo_mysql
    database_driver_class: ~
    database_host: null
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: XXX

    database_path: null
    database_table_prefix: wallabag_
    database_socket: "/var/run/mysql/mysql.sock"
    # with PostgreSQL and SQLite, you must set "utf8"
    # database_charset: utf8
    database_charset: utf8mb4

    domain_name: https://wallabag.example.net
    server_name: "Wall-a-bag"

    mailer_transport:  smtp
    mailer_user:       ~
    mailer_password:   ~
    mailer_host:       127.0.0.1
    mailer_port:       false
    mailer_encryption: ~
    mailer_auth_mode:  ~

    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: XXX

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: wallabag+2fa@example.net

    # fosuser stuff
    fosuser_registration: true
    fosuser_confirmation: true

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: wallabag@example.net

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null


    # sentry logging
    sentry_dsn: ~
    # sites credentials
    sites_credentials:
      - example.com: {XXX}
  ```
</details>

### What steps will reproduce the bug?

When trying to sync https://www.linkedin.com/pulse/uncertain-futures-using-chatgpt-generate-risk-fair-inputs-whitsitt/ from the Android app, or reload it in the web UI, the following error shows in the logs. This leads to a 500 page in the web UI, and prevents the Android app from syncing in either direction.

```
[2022-12-25 12:53:00] app.DEBUG: DownloadImages: working on image: //:0 [] []
[2022-12-25 12:53:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unable to parse URI: //:0" at /srv/www/wallabag/vendor/guzzlehttp/psr7/src/Uri.php line 72 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to parse URI: //:0 at /srv/www/wallabag/vendor/guzzlehttp/psr7/src/Uri.php:72)"} []
```

The offending string is indeed present in the original HTML of the page, as the `src` of some `imgs`, e.g., 

```<img alt="No alt text provided for this image" data-media-urn="" data-li-src="https://media.licdn.com/dms/image/D4E12AQFHkU7s2QVJMA/article-inline_image-shrink_1000_1488/0/1671326554436?e=1677110400&amp;v=beta&amp;t=WrBao1v9HjW_Zh-3N7VmMP-AVXsB8w0oRPtmcsLzlqM" src="//:0">
```

I guess this Exception should be caught, and failed gracefully on, rather than let it bubble up.
