### ISSUE TITLE
The 2.5.3 tar.gz package is targetting master instead of 2.5.3 tag

### ISSUE THREAD

**Issue by rain0r** [wallabag/wallabag#6269]
### Environment

* **Version**: 2.5.3 - 2023-02-01
* **Installation**: `git clone` and `make install`
* **PHP version**: 8.1.14
* **OS**: Gentoo Linux
* **Database**: PostgreSQL 15
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: 
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: localhost
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret:
    twofactor_auth: false
    twofactor_sender: 
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: 
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
    server_name: 'Your wallabag instance'
  ```
</details>

### What steps will reproduce the bug?

When opening Wallabag, this error is thrown:

```
2023/02/01 23:20:40 [error] 702#0: *1265 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "scheb_two_factor.security.google_authenticator". in /srv/www/wallabag.example.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1030
Stack trace:
#0 /srv/www/wallabag.example.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(1066): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 /srv/www/wallabag.example.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(346): Symfony\Component\DependencyInjection\ContainerBuilder->findDefinition()
#2 /srv/www/wallabag.example.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(96): Symfony\Component\DependencyInjection\Compiler\AutowirePass->getAutowiredReference()
#3 /srv/www/wallabag.example.com/vendor/symfony/symfony/src/Symfony/C" while reading response header from upstream, client: , server: wallabag.example.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm8.1.socket:", host: "wallabag.example.com"
```

Edit: Installation via `wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package` works.
