### ISSUE TITLE
Activating some links with the return key throws an error

### ISSUE THREAD

**Issue by vojtapolasek** [wallabag/wallabag#6333]
### Environment

* **Version**: 2.5.4
* **Installation**: docker image provided by Wallabag
* **PHP version**: provided in the container
* **OS**: CentOS Stream 9
* **Database**: Postgresql
* **Parameters**:

<details>
This is my docker-compose.yml.

  ```
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=censored
      - POSTGRES_USER=censored
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=censored
      - SYMFONY__ENV__DATABASE_PASSWORD=censored
      - SYMFONY__ENV__DATABASE_CHARSET=utf8
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@vojtapolasek.eu
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.vojtapolasek.eu
      - SYMFONY__ENV__SERVER_NAME=wallabag.vojtapolasek.eu
      - VIRTUAL_HOST=wallabag.vojtapolasek.eu
      - LETSENCRYPT_HOST=wallabag.vojtapolasek.eu
    expose:
      - "80"
    volumes:
      - censored
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=censored
      - POSTGRES_USER=censored
    volumes:
      - censored
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

networks:
  default:
    external:
      name: nginx-proxy

  ```
</details>

### What steps will reproduce the bug?

1. open some article within wallabag.
2. use TAB and SHIFT+TAB key to move around links. Move to the link "Delete"
3. press RETURN

Results:
An Error page appears. It is standard "server not found."
The URL of the page is 
```
https://wallabag.vojtapolasek.euundefined/
```

Expected result:
The confirmation dialog appears and the page can be deleted.
