### ISSUE TITLE
Attempted to call function "mb_regex_encoding" from namespace "Readability"

### ISSUE THREAD

**Issue by mart-e** [wallabag/wallabag#6343]
### Environment

* **Version**: 2.5.4
* **Installation**: source code
* **PHP version**: `7.4.33-5+0~20230214.77+debian10~1.gbpa1ea7f`
* **OS**: debian buster (10)
* **Database**: sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ...
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    domain_name: 'https://read.mart-e.be'
    server_name: 'mart-e read list'
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null

  ```
</details>

### What steps will reproduce the bug?

- Go to an article
- Click on the bookmarklet link
- Land on `https://read.mart-e.be/bookmarklet?url=https%3A%2F%2Fwww.nextinpact.com%2Farticle%2F71121%2Fquelle-heure-est-il-sur-lune` with an error:

> 500: Internal Server Error
>
> Attempted to call function "mb_regex_encoding" from namespace "Readability". Did you mean to call "\safe\mb_regex_encoding"?

I recently upgraded from debian 9 to 10, php 7 to 7.4 and wallabag 2.3 to 2.5

Thank you
