### ISSUE TITLE
CORS Missing Allow Origin

### ISSUE THREAD

**Issue by kapitanluffy** [wallabag/wallabag#6496]
<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>

  ```
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=kapitanluffy@gmail.com
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.15:8082
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
    ports:
      - 8082:80
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=wallaroot
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  pg_data:
  ```
</details>

### What steps will reproduce the bug?

I just spun up the docker compose file and it does not fetch the font assets remotely. It only happens to fonts

![image](https://user-images.githubusercontent.com/485799/236660239-b6c993a9-e5a6-4b8f-8f5b-c9984d4a2cbb.png)
