### ISSUE TITLE
bin/console cache:clear --env=prod

### ISSUE THREAD

**Issue by fate-think** [wallabag/wallabag#6508]
### Environment

* **Version**: 2.5.4
* **Installation**: git clone
* **PHP version**: 8.1
* **OS**: ubuntu 22.04
* **Database**: mysql 8.0.33
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  # This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: #sensitive
    database_user: #sensitive
    database_password: #sensitive
    database_path: /var/lib/mysql/wallabag
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: #sensitive
    server_name: #sensitive
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```
</details>

### What steps will reproduce the bug?
when I execute
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist

### errors below:
bin/console cache:clear --no-warmup

In DefinitionErrorExceptionPass.php line 54:
  Class "Doctrine\Bundle\Fixtu
  resBundle\Fixture" not found
   while loading "Wallabag\Ann
  otationBundle\DataFixtures\A
  nnotationFixtures".

Script bin/console cache:clear --no-warmup handling the post-cmd event returned with error code 1
Script @post-cmd was called via post-install-cmd
