### ISSUE TITLE
PHP Fatal error:  [...] OutOfMemoryException.php [...] while reading response header from "GET /tag/list

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#6534]
### Environment

* **Version**: 2.5.4
* **Installation**: Official Docker image 
* **PHP version**: PHP 8.1.15 (cli) (built: Feb  5 2023 22:22:23) (NTS)
* **OS**: Alpine 3.17.1 / Debian 12.0
* **Database**: MariaDB 10.11.2
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: host.docker.internal
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: XXX
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.example.net'
    server_name: Wallabag
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: XXX
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@example.net
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

  ```
</details>

### What steps will reproduce the bug?
1. Have a single user with lots of tags  (~10k) and articles linked (~22k)
```
wallabag> select count(1) from wallabag_tag
+----------+
| count(1) |
+----------+
| 9723     |
+----------+
1 row in set
Time: 0.115s
> select count(1) from wallabag_entry_tag
+----------+
| count(1) |
+----------+
| 22724    |
+----------+
1 row in set
Time: 0.054s
```
2. Hit `/tag/list`
3. Oh noes!
```
[error] 49#49: *445268 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php on line 81PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /tag/list HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.example.net", referrer: "https://wallabag.example.net/"      
```

I guess we need a bit of pagination there. Maybe also sorting the tags by number of linked articles, to get the more relevant out first.
