### ISSUE TITLE
mariadb mysql column_stats errors: hist_type and histogram are the wrong types

### ISSUE THREAD

**Issue by meonkeys** [wallabag/wallabag#6572]
I'm seeing these errors from mariadb on every page request:

```
[ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
[ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
```

### Environment

* **Version**: 2.5.4
* **Installation**: Docker image
* **PHP version**: 7.4, guessing from base image `php:7.4-fpm`
* **OS**: host is Ubuntu 22.04 LTS 64-bit server running Docker 20.10.21, build 20.10.21-0ubuntu1~22.04.3
* **Database**: mariadb 10.11.3-MariaDB-1:10.11.3+maria~ubu2204 from `mariadb` official Docker image
* **Parameters**: I haven't customized this file. I'll include my redacted `docker-compose.yml` file below.

<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>

  ```yaml
  version: '3.5'
  
  services:
    db:
      image: mariadb
      restart: unless-stopped
      volumes:
        - /data/wallabag-mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: REDACTED
        MYSQL_PASSWORD: REDACTED
        MYSQL_DATABASE: wallabag
        MYSQL_USER: wallabag
      networks:
        - wallabag
    app:
      image: wallabag/wallabag
      depends_on:
        - db
        - redis
      environment:
        SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
        SYMFONY__ENV__DATABASE_HOST: db
        SYMFONY__ENV__DATABASE_PORT: 3306
        SYMFONY__ENV__DATABASE_NAME: wallabag
        SYMFONY__ENV__DATABASE_USER: wallabag
        SYMFONY__ENV__DATABASE_PASSWORD: REDACTED
        SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
        SYMFONY__ENV__REDIS_HOST: redis
        SYMFONY__ENV__REDIS_PASSWORD: REDACTED
        SYMFONY__ENV__MAILER_HOST: mail
        SYMFONY__ENV__MAILER_USER: ~
        SYMFONY__ENV__MAILER_PASSWORD: ~
        SYMFONY__ENV__FROM_EMAIL: redacted@example.com
        SYMFONY__ENV__TWOFACTOR_AUTH: 'true'
        SYMFONY__ENV__FOSUSER_REGISTRATION: 'false'
        SYMFONY__ENV__FOSUSER_CONFIRMATION: 'true'
        SYMFONY__ENV__DOMAIN_NAME: https://wallabag.example.com
        POPULATE_DATABASE: 'no'
      volumes:
        - /data/wallabag/data:/var/www/wallabag/data
        - /data/wallabag/images:/var/www/wallabag/web/assets/images
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wallabag-https.entrypoints=websecure"
        - "traefik.http.routers.wallabag-https.rule=Host(`wallabag.example.com`)"
        - "traefik.http.routers.wallabag-https.tls.certresolver=myresolver"
      networks:
        - wallabag
        - traefik_default
        - mail_default
      restart: unless-stopped
    redis:
      image: redis:alpine
      restart: unless-stopped
      command: redis-server --requirepass REDACTED
      networks:
        - wallabag
  networks:
    wallabag:
      name: wallabag
    traefik_default:
      external: true
    mail_default:
      external: true
  ```
</details>

### What steps will reproduce the bug?

Request any page.

### See also

https://help.nextcloud.com/t/incorrect-definition-of-table-mysql-column-stats-expected-column-histogram-at-position-10-to-have-type-longblob-found-type-varbinary-255/145513
