### ISSUE TITLE
server error - out of memory - trying to add a new entry

### ISSUE THREAD

**Issue by meonkeys** [wallabag/wallabag#6573]
When I try to add a new entry I get a white page in my web browser. This is just using the web app, not the android app or the browser extension. I've been using Wallabag without issues for about 2 1/2 years without issues. I've upgraded a few times. First I've seen this particular problem.

The server log shows:

```
[error] 49#49: *337 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /var/www/wallabag/src/Wallabag/CoreBundle/Helper/DownloadImages.php on line 178PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1" while reading response header from upstream, client: 172.27.0.6, server: _, request: "POST /new-entry HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.example.com", referrer: "https://wallabag.example.com/unread/list"
```

### Environment

* **Version**: 2.5.4
* **Installation**: Docker image
* **PHP version**: 7.4, guessing from base image `php:7.4-fpm`
* **OS**: host is Ubuntu 22.04 LTS 64-bit server running Docker 20.10.21, build 20.10.21-0ubuntu1~22.04.3
* **Database**: mariadb 10.11.3-MariaDB-1:10.11.3+maria~ubu2204 from `mariadb` official Docker image
* **Parameters**: I haven't customized this file. I'll include my redacted `docker-compose.yml` file below.

<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>

  ```yaml
  version: '3.5'
  
  services:
    db:
      image: mariadb
      restart: unless-stopped
      volumes:
        - /data/wallabag-mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: REDACTED
        MYSQL_PASSWORD: REDACTED
        MYSQL_DATABASE: wallabag
        MYSQL_USER: wallabag
      networks:
        - wallabag
    app:
      image: wallabag/wallabag
      depends_on:
        - db
        - redis
      environment:
        SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
        SYMFONY__ENV__DATABASE_HOST: db
        SYMFONY__ENV__DATABASE_PORT: 3306
        SYMFONY__ENV__DATABASE_NAME: wallabag
        SYMFONY__ENV__DATABASE_USER: wallabag
        SYMFONY__ENV__DATABASE_PASSWORD: REDACTED
        SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
        SYMFONY__ENV__REDIS_HOST: redis
        SYMFONY__ENV__REDIS_PASSWORD: REDACTED
        SYMFONY__ENV__MAILER_HOST: mail
        SYMFONY__ENV__MAILER_USER: ~
        SYMFONY__ENV__MAILER_PASSWORD: ~
        SYMFONY__ENV__FROM_EMAIL: redacted@example.com
        SYMFONY__ENV__TWOFACTOR_AUTH: 'true'
        SYMFONY__ENV__FOSUSER_REGISTRATION: 'false'
        SYMFONY__ENV__FOSUSER_CONFIRMATION: 'true'
        SYMFONY__ENV__DOMAIN_NAME: https://wallabag.example.com
        POPULATE_DATABASE: 'no'
      volumes:
        - /data/wallabag/data:/var/www/wallabag/data
        - /data/wallabag/images:/var/www/wallabag/web/assets/images
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wallabag-https.entrypoints=websecure"
        - "traefik.http.routers.wallabag-https.rule=Host(`wallabag.example.com`)"
        - "traefik.http.routers.wallabag-https.tls.certresolver=myresolver"
      networks:
        - wallabag
        - traefik_default
        - mail_default
      restart: unless-stopped
    redis:
      image: redis:alpine
      restart: unless-stopped
      command: redis-server --requirepass REDACTED
      networks:
        - wallabag
  networks:
    wallabag:
      name: wallabag
    traefik_default:
      external: true
    mail_default:
      external: true
  ```
</details>

### What steps will reproduce the bug?

Try to add a new entry.

### See also

https://github.com/wallabag/docker/issues/124

**Comment by nicosomb** [comment]
Hello @meonkeys 

Do you still have the bug (with latest wallabag version)?
If yes, with all the URL, or just one? 
Is that a docker-side issue?

**Comment by megamorf** [comment]
I have this problem with dockerized 2.6.9:

```
2024/09/05 19:45:37 [error] 59#59: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 59520000 bytes) in /var/www/wallabag/src/Wallabag/CoreBundle/Helper/DownloadImages.php on line 182" while reading response header from upstream, client: 192.168.39.20, server: _, request: "POST /new-entry HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.example.org", referrer: "https://wallabag.example.org/"
```

docker-compose.yml

```yml
services:
  wallabag:
    image: wallabag/wallabag:2.6.9
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_ROOT_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=${WALLABAG_DB}
      - SYMFONY__ENV__DATABASE_USER=${WALLABAG_DB_USERNAME}
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.org
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.org
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    ports:
      - "8082:80"
    volumes:
      - ./data/images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.5
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      MYSQL_ROOT_PASSWORD: "${WALLABAG_DB_ROOT_PASSWORD}"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
```

URL with which the error occurred: https://stack-auth.com/blog/oauth-from-first-principles
