### ISSUE TITLE
Wallabag 2.6.2 CSS not loading in admin panel

### ISSUE THREAD

**Issue by jameswill** [wallabag/wallabag#6755]
### Environment

* **Version**: 2.6.2
* **Installation**: Downloading the package
* **PHP version**: 7.4
* **Database**: 5.7.42
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag262
    database_user: root
    database_password: mysql
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'http://example.com/wallabag262/web'
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```
</details>

### What steps will reproduce the bug?

I have downloaded the package using wget **https://www.wallabag.org/latest-v2-package** and installed it on my test server with above details. However after completing the installation when I visit the admin panel, it's CSS seems to be broken throwing following error in console.

**_Uncaught ReferenceError: fos is not defined
    <anonymous> http://example.com/wallabag262/web/js/routing?callback=fos.Router.setData:1_**

![wallabag](https://github.com/wallabag/wallabag/assets/6368036/f0044518-c16a-442b-8da1-8bb54f3d4886)
