### ISSUE TITLE
Default user not created

### ISSUE THREAD

**Issue by cbirkenbeul** [wallabag/wallabag#6795]
### Environment

* **Version**: 2.6.2
* **Installation**: Docker
* **PHP version**:
* **OS**:
* **Database**: Postgres
* **Parameters**:

### What steps will reproduce the bug?
I also had issues with creating the necessary database tables. The comment in #6649 helped me with that. Now I have the tables populated, but the wallabag_users Tables is empty. How could I create the default user or some others? I've look in the repo to findet the database command for creating the wallabag user, but did not find it.
Thanks.

**Comment by nicosomb** [comment]
Hello @cbirkenbeul ! 

To reinstall fixtures, you can execute `bin/console wallabag:install -e prod` (or `bin/console wallabag:install` if you are in development mode).

**Comment by cbirkenbeul** [comment]
Hey. Thanks for your fast help. Unfortunately that did not work
```
wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------ -------- ----------------
  Checked                  Status   Recommendation
 ------------------------ -------- ----------------
  PDO Driver (pdo_pgsql)   OK!
  Database connection      OK!
  Database version         OK!
  curl_exec                OK!
  curl_multi_init          OK!
 ------------------------ -------- ----------------


 [OK] Success! Your system can run wallabag properly.


Step 2 of 4: Setting up database.
---------------------------------

 It appears that your database already exists. Would you like to reset it? (yes/no) [no]:
 > yes

 Dropping database, creating database and schema...

In InstallCommand.php line 361:

  The command "doctrine:database:drop" generates some errors:

  Could not drop database /var/www/wallabag/app/../data/db/wallabag.sqlite for connection named default
  An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "/"
  LINE 1: DROP DATABASE /var/www/wallabag/app/../data/db/wallabag.sqli...
  ```

**Comment by nicosomb** [comment]
Hmm I read `Database: Postgres` in your first post and I see `sqlite` in your last one. 

Could you copy/paste your `app/config/parameters.yml` file here please?

**Comment by cbirkenbeul** [comment]
Sure:
```
parameters:
    database_driver: pdo_pgsql
    database_host: pgsql01.internaldomain
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: PASSWORD
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.example.com'
    server_name: Wallabag
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: SECRET
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```
