### ISSUE TITLE
Unable to fetch API token with Wallabagger after 2.6.3 upgrade

### ISSUE THREAD

**Issue by 4oo4** [wallabag/wallabag#6865]
https://github.com/wallabag/wallabagger/issues/363

I noticed I can't use the Wallabagger extension anymore after upgrading, because it fails to fetch an API token. My other API integrations and the Wallabag app are still working though.

### Environment

* **Version**: 2.6.3
* **Installation**: Git
* **PHP version**: 8.1.22
* **OS**: Alpine 3.16
* **Database**: mariadb 10.6.14
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
  parameters:
    database_driver: pdo_mysql
    database_host: 10.0.3.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: REDACTED
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    locale: en
    secret: REDACTED
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: 10.0.3.2
    redis_port: 6379
    redis_path: null
    redis_password: REDACTED
    domain_name: 'https://wallabag.example.com/'
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
```
</details>

### What steps will reproduce the bug?
- Upgrade to 2.6.3
- Attempt to fetch token with Wallabagger
