### ISSUE TITLE
Unable to send emails via "gmail" as the bridge is not installed

### ISSUE THREAD

**Issue by lockheed** [wallabag/wallabag#6898]
Encouraged by the recent praise from Late Night Linux, I installed Wallabag by docker-compose. 

However, I was unable to register an account, because as soon as I enter the account details and click Register, I get this:

![image](https://github.com/wallabag/docker/assets/3472480/f735b8e0-6460-45cd-9217-4c5259b241f1)

This is my docker-compose
```
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      - SYMFONY__ENV__MAILER_DSN=gmail+smtp://wallaxxx:zzcxasfawfaegf@default
      - SYMFONY__ENV__FROM_EMAIL=wallaxxx@gmail.com
      - SYMFONY__ENV__DOMAIN_NAME=https://walla.mydomain.com
      - SYMFONY__ENV__SERVER_NAME="Wallabag"
    volumes:
      - /z/services/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    networks:
      - frontend

networks:
  frontend:
    external: true

```
