### ISSUE TITLE
Docker instance fails to start with MAILER_DSN that contains URL-encoded string ("%")

### ISSUE THREAD

**Issue by jluo98** [wallabag/wallabag#6927]
### Environment

* **Version**: 2.6.6
* **Installation**: Docker 24.0.5 with Compose 2.20.2
* **PHP version**: php:8.1-fpm (default version in the Docker image)
* **OS**: Ubuntu 22.04.3 LTS
* **Database**: mariadb
* **Parameters**:

<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>

````
...
  wallabag:
    image: wallabag/wallabag:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./storage/wallabag/data:/var/www/wallabag/data
      - ./storage/wallabag/images:/var/www/wallabag/web/assets/images
    environment:
      SYMFONY__ENV__DOMAIN_NAME: https://example.com
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: mariadb
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: ####
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__SECRET: ####
      SYMFONY__ENV__MAILER_DSN: smtp://noreply%40example.com:fake%23password@smtp.example.com:587
      SYMFONY__ENV__FROM_EMAIL: wallabag@example.com
      SYMFONY__ENV__TWOFACTOR_SENDER: wallabag@example.com
      SYMFONY__ENV__FOSUSER_REGISTRATION: false
      POPULATE_DATABASE: false
    labels:
      - traefik.http.routers.wallabag.rule=Host(`example.com`)
      - traefik.http.routers.wallabag.tls=true
      - traefik.http.routers.wallabag.tls.certresolver=lets-encrypt
      - traefik.http.routers.wallabag.entrypoints=websecure
      - traefik.http.routers.wallabag.middlewares=domainRedirectWallabag,cloudflareWarp@file
      - traefik.http.services.wallabag.loadbalancer.server.port=80
    networks:
      - internal
      - web
    restart: always
...
````
</details>

### What steps will reproduce the bug?

* Assume the SMTP login is `noreply@example.com`, password is `fake#password`, server is `smtp.example.com`, and port is `587`
* URL Encode the user and pass: `noreply%40example.com`, `fake%23password`
* Use `SYMFONY__ENV__MAILER_DSN: smtp://noreply%40example.com:fake%23password@smtp.example.com:587` as an environment entry
* Bring up compose
* Container fails to start with the following error message: `You have requested a non-existent parameter "40example.com:fake".`
* Same error when entry is double-quoted, single-quoted, or single-quoted nested in a double quote
* Error goes away when there is no `%` in the entry, meaning any login/password that contains special characters will not work even after url-encode. 

````
Starting wallabag ...
Waiting for database ...
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/compiler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/consistency is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/event is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/exception is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/file is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/iterator is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/math is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/protocol is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/regex is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ruler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/stream is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ustring is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/visitor is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/zformat is abandoned, you should avoid using it. No replacement was suggested.
Package lexik/form-filter-bundle is abandoned, you should avoid using it. Use spiriitlabs/form-filter-bundle instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
Package wallabag/php-mobi is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/web-server-bundle is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class SimpleHtmlDom\simple_html_dom_node located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
Class SimpleHtmlDom\simple_html_dom located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
100 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> bin/console cache:clear --no-warmup

In ParameterBag.php line 95:

  You have requested a non-existent parameter "40example.com:fake".


Script bin/console cache:clear --no-warmup handling the post-cmd event returned with error code 1
Script @post-cmd was called via post-install-cmd
````
