### ISSUE TITLE
Tagging multiple entries through the API

### ISSUE THREAD

**Issue by karthink** [wallabag/wallabag#6928]
### Environment

* **Version**: 2.6.5
* **Installation**: docker image
* **PHP version**: Not sure
* **OS**: Debian Stable
* **Database**: SQLite
* **Parameters**: This is my docker-compose.yml

<details>
  <summary>My <code>docker-compose.yml</code> is:</summary>
```yaml
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__SECRET=HIDDEN
      - SYMFONY__ENV__DOMAIN_NAME="HIDDEN"
      - SYMFONY__ENV__SERVER_NAME="HIDDEN"
    ports:
      - "8012:80"
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 100m
      timeout: 3s
```
</details>

### What steps will reproduce the bug?

I'm not sure if this is a bug or if I'm just misunderstanding the API docs.  Here is the documentation for the API endpoint `/api/entries/tags/lists`:

```
Handles an entries list and add tags to them.

list: Urls (as an array) to handle. A JSON array of urls [{'url': 'http://...','tags': 'tag1, tag2'}, {'url': 'http://...','tags': 'tag1, tag2'}]
```

It's not clear to me what this means.  I took this to mean I could specify multiple existing entries and supply their urls along with the tags to add to this API endpoint.

To test this, I picked an existing entry with an `id` of 9940 and the `url` field given below in the curl command.  I want to add two tags ("later" and "testtag") to this entry.  (NOTE: I'm aware that I can do this for a single entry via the endpoint `/api/entries/{entry}/tags`, I would like to apply tags to multiple entries at once.)

From a local machine, I then run
```bash
curl -X POST \
         -H "Content-Type: application/json"
         --data '[{"url":"https://www.escapistmagazine.com/why-transparency-is-such-a-big-issue-for-the-strike-and-for-streaming/","tags":"later,testtag"}]' \
         "$WALLABAG_HOST/api/entries/tags/lists?access_token=$WALLABAG_TOKEN"
```
where `WALLABAG_HOST` and `WALLABAG_TOKEN` have their obvious meanings.

The result is:
```json
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "status": 500,
  "detail": "Internal Server Error"
}
```

Am I misunderstanding how this works?  I tried asking on Gitter yesterday but there were no responses.

Other questions about the tagging API:

1. Why is the DELETE version of this endpoint `/api/entries/tags/list` (not `lists`, like above)?  Is this a typo in the docs?
2. I can add multiple tags to a specific entry via `/api/entries/{entry}/tags`.  But there is no equivalent to removing multiple tags from a specific entry: `DELETE /api/entries/{entry}/tags/{tag}` removes only a single tag.  Is there a symmetric version of the add tags feature?
