### ISSUE TITLE
Entries do not sync if there are no more entries on the server but there still are entries in the app

### ISSUE THREAD

**Issue by Shocker** [wallabag/wallabag#6931]
### Environment

* **Version**: 2.6.5 (6b7e9ec1df4235ce77cad3f36055dad59151dbaf)
* **Installation**: git clone + make install
* **PHP version**: 7.4
* **OS**: Ubuntu 20.04
* **Database**: MySQL 5.7.40

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: ***
    database_port: ***
    database_name: ***
    database_user: ***
    database_password: ***
    database_path: null
    database_table_prefix: ***
    database_socket: null
    database_charset: utf8mb4
    domain_name: '***'
    server_name: Wallabag
    mailer_dsn: '***'
    locale: en
    secret: ***
    twofactor_sender: ***
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: ***
    rss_limit: 50
    rabbitmq_host: ***
    rabbitmq_port: ***
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: ***
    redis_port: ***
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?
1. Start a fresh install, empty entries database
2. Add some entries from the web or API
3. Go to phone app, sync. The entries will appear correctly
4. Delete entries from the web or API
5. Go to phone app, sync. The entries **will NOT disappear**
6. Add 1 entry from the web or API
7. Go to phone app, sync. The new entry will appear
8. Sync one more time, the old entries will correctly disappear
