### ISSUE TITLE
Docker/Ngninx instance redirecting to 127.0.0.1 despite proper env var configs

### ISSUE THREAD

**Issue by kael-shipman** [wallabag/wallabag#7019]
### Environment

* **Version**: 2.5.4
* **Installation**: Docker
* **PHP version**: 8.1.23 (from the docker container)
* **OS**:  (whatever the docker container is built on)
* **Database**: sqlite
* **Parameters**: default from docker container

### Summary

**NOTE: This may not actually be a bug per se - it may just be unclear documentation.** Basically, when I set up my deployment using stock and standard settings per the existing documentation, my system is redirecting to 127.0.0.1, despite having configured what I believe is the correct environment variable for controlling that. I've tried a couple different variables and nothing seems to be working. Details below.

### What steps will reproduce the bug?

1. Register test domain - say, wallabag.my-domain.com - and point it to a server running Ubuntu
2. (Mess with SSL setup if you want using certbot. Obviously not necessary for testing, but I just copy/pasted the files below, so it's an assumption of those files.)
3. Install Nginx and enable the service defined by the nginx file below.
4. Create the docker stack file shown below, install latest docker and run `sudo docker stack deploy -c /path/to/the/file/below.yml wallabag`
5. Navigate to `https://wallabag.my-domain.com`. It should redirect to `https://wallabag.my-domain.com/login`, but instead of redirects to `https://127.0.0.1:1111/login`, which breaks

<details>
  <summary>Docker Stack File</summary>

```yml
version: "3.9"

services:
    wallabag:
        image: wallabag/wallabag
        ports:
            - "1111:80"
        volumes:
            - /home/me/wallabag:/var/www/wallabag/data/db
        environment:
            # This is the one env var that SHOULD affect this configuration, as it appears directly in the codebase in the parameters.yml file, but it doesn't seem to work
            - DOMAIN_NAME=https://wallabag.my-domain.com
            # This is just for thoroughness
            - SERVER_NAME=wallabag.my-domain.com

            # Google suggested this, and I've seen it before, but I couldn't find it in the codebase. It didn't work (at least not with these values, which may be wrong)
            - TRUSTED_PROXIES=127.0.0.1/8,10.0.0.2/8

            # These two appear to be legacy. I've tried it both with and without them
            - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.my-domain.com
            - SYMFONY__ENV__SERVER_NAME=wallabag.my-domain.com
```
</details>

<details>
  <summary>Nginx config file</summary>

```nginx
# Wallabag
server {
  listen 80;
  server_name wallabag.my-domain.com;
  return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name wallabag.my-domain.com;
    root /srv/www/wallbag.my-domain.com/web;

    include conf.d/my-domain.certs.local;
    include global_restrictions.conf;

    location / {
        proxy_pass http://127.0.0.1:1133;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    error_log /var/log/nginx/err_wallabag.my-domain.com.log;
    access_log /var/log/nginx/err_wallabag.my-domain.com.log;
}
```
</details>

**Comment by kael-shipman** [comment]
The plot thickens... On the local machine, when I run `curl -I http://localhost:1111` (to access the docker container directly), the call hangs. However, when I add `127.0.0.1 wallabag.my-domain.com` to my `/etc/hosts` file and then run `curl -I http://wallabag.my-domain.com:1111`, it works, and not only, but the `Location` header is correct!

So I've learned three things from this:

1. wallabag itself is doing some sort of requesting-domain analysis to determine whether or not to respond;
2. wallabag is employing some similar request-analysis logic to determine the appropriate redirect address; and
3. the redirect address is calculated incorrectly only when it is interfaced using an nginx reverse proxy.

**Comment by kael-shipman** [comment]
Really getting hacky here, but I exec'd into the running docker container and edited `vendor/symfony/http-foundation/RedirectResponse.php` to replace `127.0.0.1:1111` with `wallabag.my-domain.com` for all redirect requests. This worked, but now when I try to log in with successful credentials, it just redirects back to the login page again with the message `Authentication request could not be processed due to a system problem.` However, I see no errors in the docker logs, nor do I see anything logged in the JS console. I can't figure out where that text is coming from or how to get access to the underlying server error.

Of course, this is not intended to be a long-term solution - it's just some probing I was doing, and it seems to suggest a broader issue.

For what it's worth, I ran into this problem a year ago when I first converted to docker deploys. I don't remember how I got past it, but I did something hacky to log in, and once I was logged in it worked fine (probably because there were no redirects after that).

**Comment by kael-shipman** [comment]
Ok.... so doing the above actually DID get me logged in, but only after I manually executed a database migration via [this comment](https://github.com/wallabag/wallabag/issues/6649#issuecomment-1616021842).

Gonna just leave at this for now, but I would love some input as to how to fix this problem more long-term. I'm sure this is just a simple documentation issue around env vars, but I can't figure it out.

**Comment by j0k3r** [comment]
This is really an obscur issue. I think the problem is around the mapping ports (1111:80) and maybe something within Symfony (the framework used by wallabag).
Maybe, [switching to the new Symfony local server](https://github.com/wallabag/wallabag/pull/6850) will fix the problem.

**Comment by Mikesco3** [comment]
I just tried the docker compose install and it comes up but the html is badly broken...
![image](https://github.com/wallabag/wallabag/assets/13419518/11d7ba10-5b99-484b-b688-f79fc4a3d25c)

Here is the docker compose I was trying to use:
```
version: "3.3"
services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag:2.4.1
    links:
      - wallabag-db:wallabag-db
    environment:
      - TZ=America/Chicago
      - POSTGRES_PASSWORD=my_super_secret_password
      - POSTGRES_USER=my_db_user
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=my_db_user
      - SYMFONY__ENV__DATABASE_PASSWORD=my_super_secret_password
      - SYMFONY__ENV__DOMAIN_NAME=http://localhost
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/web/assets/images      
    ports:
      - 3080:80
    depends_on:
      - wallabag-db
  wallabag-db:
    container_name: wallabag-db
    environment:
      - POSTGRES_PASSWORD=my_super_secret_password
      - POSTGRES_USER=my_db_user
    image: postgres:9.6
networks: {}
```
