### ISSUE TITLE
Invalid datetime format while adding URL

### ISSUE THREAD

**Issue by alpacathunder1** [wallabag/wallabag#7048]
### Environment

* **Version**: 2.6.7
* **Installation**: Docker
* **PHP version**: PHP 8.1.23 (included in the container)
* **OS**: Debian 12
* **Database**: MariaDB (the [Linuxserver.io Container](https://hub.docker.com/r/linuxserver/mariadb), `mariadb --version` in the container says:  `mariadb  Ver 15.1 Distrib 10.11.5-MariaDB, for Linux (x86_64) using readline 5.1`
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
parameters:
    database_driver: pdo_mysql
    database_host: mariadb_wallabag
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: REDACTED
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: REDACTED'
    server_name: Wallabag
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: REDACTED
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```
</details>

### What steps will reproduce the bug?

Adding `https://www.tofugu.com/japanese/onyomi-kunyomi/` to my wallabag instance gives the following Database error:

```

500: Internal Server Error

An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8D\xAA e...' for column `wallabag`.`wallabag_entry`.`content` at row 1
```

It seems to work with other Tofugu urls.

Thanks for reading, let me know if I can help debug it.
