### ISSUE TITLE
Doesn't respect port

### ISSUE THREAD

**Issue by realpixelcode** [wallabag/wallabag#7259]
### Environment

* **Version**: 2.6.8
* **Installation**: `make install`
* **PHP version**: 8.2.7
* **OS**: Raspberry Pi OS Bookworm, Kernel `6.1.0-rpi6-rpi-v8`
* **Database**: `mysql  Ver 15.1 Distrib 10.11.6-MariaDB`
* **Parameters**: `domain_name: 'https://wallabag.example.org:1234`

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
 parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wb
    database_password: ...
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.example.org:1234'
    server_name: 'Wallabag'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: de
    secret: ...
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

0. Set up Wallabag for the first time.
1. Include a port number in the domain name.
2. Visit that base URL (initial login page).
3. Wallabag tries to fetch
  - `material.css`
  - `router.js`
  - `material.js`
  - `logo-wallabag.svg`
  - `apple-touch-icon-152.png`
  - `favicon.ico`
  from `wallabag.example.org` instead of `wallabag.example.org:1234`.

That's an issue when you're already using the 80 and 443 ports for something else.
