### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by grayguest** [wallabag/wallabag#7322]
### Environment

* **Version**: 2.6.8
* **Installation**: git clone
* **PHP version**: PHP 7.4.33 (cli) (built: Mar 31 2023 13:12:30) ( NTS )
* **OS**: Linux Mint 21 x86_64 
* **Database**: mysql  Ver 14.14 Distrib 5.7.41, for linux-glibc2.12 (x86_64) using  EditLine wrapper
* **Parameters**: 
<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
        database_driver: pdo_mysql
        database_host: 127.0.0.1
        database_port: 3306
        database_name: wallabag
        database_user: root
        database_password: password
        database_path: null
        database_table_prefix: wallabag_
        database_socket: null
        database_charset: utf8mb4
        domain_name: 'http://wallabag.xiaopo'
        server_name: wallabag.xiaopo
        mailer_dsn: 'smtp://127.0.0.1'
        locale: en
        secret: password
        twofactor_sender: no-reply@wallabag.org
        fosuser_registration: true
        fosuser_confirmation: true
        fos_oauth_server_access_token_lifetime: 3600
        fos_oauth_server_refresh_token_lifetime: 1209600
        from_email: no-reply@wallabag.org
        rss_limit: 50
        rabbitmq_host: localhost
        rabbitmq_port: 5672
        rabbitmq_user: xiaopo
        rabbitmq_password: password
        rabbitmq_prefetch_count: 10
        redis_scheme: tcp
        redis_host: localhost
        redis_port: 6379
        redis_path: null
        redis_password: password
        sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

When I finish the `make install`, visit the http://wallabag.xiaopo/, It will tips
![image](https://github.com/wallabag/wallabag/assets/10668340/3a1ebe81-018d-4fd2-9ca5-f5c1a5b8ca63)
