### ISSUE TITLE
Development docker image always reports "Authentication request could not be processed due to a system problem."

### ISSUE THREAD

**Issue by GiovanH** [wallabag/wallabag#7352]
Locally testing the server using docker (as per https://github.com/wallabag/wallabag/blob/master/.github/CONTRIBUTING.md#using-docker) always throws the error "Authentication request could not be processed due to a system problem." when trying to authenticate at the login page. 

Confirmed with an existing database and also a brand new sqlite database created with new user wallabag/wallabag. 

As far as I can tell there is no useful output in any logs. 

### Environment

* **Version**: git master
* **Installation**: N/A
* **PHP version**: 
* **OS**:
* **Database**:
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: ~
    database_name: symfony
    database_user: root
    database_password: ~
    database_path: 'wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8

    domain_name: http://garnet:8002
    server_name: "Your wallabag instance"

    mailer_dsn: "smtp://127.0.0.1"

    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv

    # two factor stuff
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_registration: false
    fosuser_confirmation: true

    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: wallabag@example.com

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: rabbitmq
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: ~
    redis_password: ~

    # Sentry
    sentry_dsn: ~

```
</details>
