### ISSUE TITLE
Issues with redirect when marking article as read

### ISSUE THREAD

**Issue by 4oo4** [wallabag/wallabag#7418]
### Environment

* **Version**: 2.6.9
* **Installation**: git clone
* **PHP version**: 8.1.28
* **OS**: Alpine 3.19
* **Database**: mariadb
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
parameters:
    database_driver: pdo_mysql
    database_host: 10.0.11.10
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: XXXXXXXXXXXXXXXX
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    locale: en
    secret: XXXXXXXXXXXXXXXX
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: 10.0.3.59
    redis_port: 6379
    redis_path: null
    redis_password: XXXXXXXXXXXXXXXX
    domain_name: 'https://wallabag.example.com/'
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
```

</details>

### What steps will reproduce the bug?
When I click on mark as read on an article, I see a `?redirect` parameter (related to https://github.com/wallabag/wallabag/pull/7140) that looks like it should take me back to the page that I was on, but looking at the response headers instead I see a `location: /` header, which redirects me back to the main page instead of keeping my place.
```
GET /archive/58019?redirect=/5 HTTP/2
Host: wallabag.example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://wallabag.example.com/5
DNT: 1
Connection: keep-alive
Cookie: PHPSESSID=XXXXXXXXXXXXXX; REMEMBERME=XXXXXXXXXXXXXXXXXXXXX
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
------------------------
HTTP/2 302 
server: nginx
date: Thu, 11 Apr 2024 16:20:30 GMT
content-type: text/html; charset=UTF-8
cache-control: max-age=0, must-revalidate, private
pragma: no-cache
expires: Thu, 11 Apr 2024 16:20:30 GMT
location: /
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-robots-tag: noindex,nofollow
x-dns-prefetch-control: content=on
expect-ct: enforce,max-age=30
permissions-policy: interest-cohort=()
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-robots-tag: noindex,nofollow
x-dns-prefetch-control: content=on
expect-ct: enforce,max-age=30
permissions-policy: interest-cohort=()
X-Firefox-Spdy: h2
```
