### ISSUE TITLE
Can't fetch hellofresh rezept (www.hellofresh.de)

### ISSUE THREAD

**Issue by GAS85** [wallabag/wallabag#7451]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.hellofresh.de/recipes/asiatische-hahnchenbrust-mit-edamame-609135de690cc71eea1fc4c9
 - wallabag version: 2.6.9

**Describe what's wrong:**
Instead of Rezeipt I've got this:
![изображение](https://github.com/wallabag/wallabag/assets/6813635/4749cc64-afa7-46a5-abbf-446fd6fad1c3)
But the tail preview is correct:
![изображение](https://github.com/wallabag/wallabag/assets/6813635/26affdd8-f8eb-4ac0-963f-75f67b5e2073)

**Comment by HolgerAusB** [comment]
The general problem with most cooking receipt website, are their interactive elements for choosing the amount of servings which is re-calculating the amount of ingredients. Same for nutritional values per serving or per 100g.

I can't catch the text from their buttons, so only the 1st option is fetched for wallabag. My config doesn't make the page pretty, but everything important should be in.

**Comment by GAS85** [comment]
Hey, if I "reload" this page I do not see the content.
What I did:
1. Based on https://github.com/wallabag/wallabag/issues/5147#issuecomment-1518605866 I cloned the repository:
```bash
sudo -u docker git clone https://github.com/fivefilters/ftr-site-config.git
# I change ownership as inside of containers for other folders
chown nobody:nogroup -R vendor
```
2. I mounted it the wallabag:
```yaml
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    container_name: wallabag
    environment:
      ...
    volumes:
      - ${WORKINGDIR}/docker/wallabag/images:/var/www/wallabag/web/assets/images
      # see https://github.com/wallabag/wallabag/issues/5147
      # Filters are at https://github.com/fivefilters/ftr-site-config
      - ${WORKINGDIR}/docker/wallabag/vendor/ftr-site-config:/var/www/wallabag/vendor/ftr-site-config
```
3. I can see it inside of container after restart:
```bash
docker exec wallabag ls -la vendor | grep ftr-site-config
drwxrwxr-x    3 nobody   nobody       73728 Jun 20 19:42 ftr-site-config
```
4. If I click on reload, I still se no content and error in logs:
```bash
2024/06/20 20:06:56 [error] 60#60: *9 FastCGI sent in stderr: "PHP message: PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /var/www/wallabag/vendor/hoa/stream/Stream.php on line 195" while reading response header from upstream, client: 172.18.0.32, server: _, request: "GET /reload/35 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.myhome:9070", referrer: "http://wallabag.myhome:9070/view/35"
```

**Comment by j0k3r** [comment]
You should instead clone https://github.com/j0k3r/graby-site-config

**Comment by GAS85** [comment]
Thanks! Just saw this too... 😄  After cloning repo that you linked, correct config will be:
```yaml
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    container_name: wallabag
    environment:
      ...
    volumes:
      - ${WORKINGDIR}/docker/wallabag/images:/var/www/wallabag/web/assets/images
      # see https://github.com/wallabag/wallabag/issues/5147
      # Filters are at https://github.com/j0k3r/graby-site-config
      - ${WORKINGDIR}/docker/wallabag/vendor/graby-site-config:/var/www/wallabag/vendor/j0k3r/graby-site-config
```
It is also referenced here: https://github.com/wallabag/wallabag/blob/5da3772f3bcdc198b1dac2555d87b307e8000f34/docker-compose.yml#L21
