### ISSUE TITLE
API/documentation: Add OpenAPI JSON endpoint

### ISSUE THREAD

**Issue by voltagex** [wallabag/wallabag#7462]
**Is your feature request related to a problem? Please describe.**
If there's an OpenAPI 3 JSON specification available, I can automatically generate part of a Wallabag client (or even an API compatible server!)

It's supported by the Nelmio library you're using, but not turned on.

**Describe the solution you'd like**
It looks like https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#installation says that you need something as "simple" as 

```
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```
next to https://github.com/wallabag/wallabag/blob/master/app/config/routing.yml#L5 but I don't know how to do it with the syntax you're using.

**Describe alternatives you've considered**
Learning enough about Symphony and hacking routing.yaml myself
