### ISSUE TITLE
Setting "export_mobi" couldn't be found after login

### ISSUE THREAD

**Issue by lucker999** [wallabag/wallabag#7478]
Thank you for reporting an issue.

Please fill in as much of the template below as you're able.

Version:      2.6.9
Installation: git clone (rather old installation), upgraded with `make upgrade`
PHP version:  8.3
OS:           FreeBSD, in a jail
Database:     postgres 15
Parameters:   see below

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: 10.1.1.22
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: pa$$w0rd
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://some.domain.com'
    server_name: 'Wallabag'
    locale: en
    secret: SecrETkeY
    twofactor_sender: some@address.com
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@shershidsky.eu
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: 10.1.1.232
    redis_port: 6379
    redis_path: null
    redis_password: sOmE_pass
    sentry_dsn: null
    mailer_dsn: 'smtp://account_data'
  ```
</details>

### What steps will reproduce the bug?

I migrated from the server with rather an old installation (AFAIR last time Wallabag was updated ca. Feb-March 2023) on a freshly installed FreeBSD in jail. I ran `make update`, all went smoothly, but there were some warnings:
```
 68/85 [======================>-----]  80%  - Installing symfony/google-mailer (v4.4.41): Extracting archive
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/compiler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/consistency is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/event is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/exception is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/file is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/iterator is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/math is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/protocol is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/regex is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ruler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/stream is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ustring is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/visitor is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/zformat is abandoned, you should avoid using it. No replacement was suggested.
Package lexik/form-filter-bundle is abandoned, you should avoid using it. Use spiriitlabs/form-filter-bundle instead.
Package php-http/guzzle5-adapter is abandoned, you should avoid using it. Use php-http/guzzle7-adapter instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package scheb/2fa-qr-code is abandoned, you should avoid using it. No replacement was suggested.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
Package wallabag/php-mobi is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/web-server-bundle is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class SimpleHtmlDom\simple_html_dom_node located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
Class SimpleHtmlDom\simple_html_dom located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
```
After login I immediately redirected on the main URI (https://domain.com) which displays 500: Internal Server Error:
An exception has been thrown during the rendering of a template ("Setting "export_mobi" couldn't be found.")
![Screenshot 2024-05-14 19 49 10](https://github.com/wallabag/wallabag/assets/9690776/7af9fde8-e28e-454f-b906-92fbf8940e92)

Since there is no links on the page, I tried to enter domain.com/new and it got me to the page with menu. I can browse settings, but any attempts to open saved articles fail.
