### ISSUE TITLE
Installation fails while connection to postgresql using ssl

### ISSUE THREAD

**Issue by IeP4nieF** [wallabag/wallabag#7496]
### Environment

* **Version**: latest (`git clone https://github.com/wallabag/wallabag.git`)
* **Installation**: ?
* **PHP version**: 8.2.18
* **OS**: Debian 12
* **Database**: PostgreSQL
* **Parameters**: ?

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  # This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_host: postgresql.domain
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: <password>
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.domain'
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://smtp.domain'
    locale: en
    secret: <secret>
    twofactor_sender: wallabag@domain
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@domain
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Try `make install` with a dedicated postgresql-host which forces ssl (`hostssl` in `pg_hab.conf`). After entering all the parameters `make install` fails with throwing an error:

    ERROR!   Can't connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "postgresql.domain" (<ip>), port 5432 failed: Fatal error: np pg_hba.conf entry for host "<ip>", user "wallabag", database "wallabag", no encryption.

Obviously wallabag tries to connect with an unencrypted connection. There is no parameter in the documentation to switch sslmode on.

**Comment by j0k3r** [comment]
I guess that you then have certificats to provide to the connection?

Can you add these lines (filled with your informations) between line 59 & 60: https://github.com/wallabag/wallabag/blob/f8f7f962cebab65d94f29e165046dc6e638d1a37/app/config/config.yml#L59C9-L59C20

```yaml
        sslmode:                  require             # PostgreSQL specific (LIBPQ-CONNECT-SSLMODE)
        sslrootcert:              postgresql-ca.pem   # PostgreSQL specific (LIBPQ-CONNECT-SSLROOTCERT)
        sslcert:                  postgresql-cert.pem # PostgreSQL specific (LIBPQ-CONNECT-SSLCERT)
        sslkey:                   postgresql-key.pem  # PostgreSQL specific (LIBPQ-CONNECT-SSLKEY)
        sslcrl:                   postgresql.crl      # PostgreSQL specific (LIBPQ-CONNECT-SSLCRL)
```

Be careful about the indentation.
