### ISSUE TITLE
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error

### ISSUE THREAD

**Issue by kalon33** [wallabag/wallabag#7684]
### Environment

* **Version**: 2.6.9
* **Installation**: git clone from stable.
* **PHP version**: 8.2.23
* **OS**: Ubuntu 22.04 LTS
* **Database**: MariaDB 10.3.39
* **Parameters**:
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: ****
    database_password: ******
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.badabam.net'
    locale: fr
    secret: *******
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: ****
    rabbitmq_port: 5672
    rabbitmq_user: ******
    rabbitmq_password: *****
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: ****
    redis_port: 6379
    redis_path: null
    redis_password: *****
    server_name: 'Wallabag de Badabam'
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    mailer_dsn: 'smtp://*****:******@smtp.****.net'
```

<details>
  [2024-09-15T06:38:17.637745+00:00] request.INFO: Matched route "api_get_entries". {"route":"api_get_entries","route_parameters":{"_route":"api_get_entries","_format":"json","_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::getEntriesAction"},"request_uri":"https://wallabag.badabam.net/api/entries.json?detail=full&order=asc&page=4&perPage=30&since=0&sort=created","method":"GET"} []
[2024-09-15T06:38:17.851777+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 42 of 42 bytes'" at /data/www/datas/wallabag/vendor/doctrine/dbal/src/Types/ConversionException.php line 117 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 42 of 42 bytes' at /data/www/datas/wallabag/vendor/doctrine/dbal/src/Types/ConversionException.php:117)"} []
</details>

### What steps will reproduce the bug?

When refreshing the list of items in android app, I got this error: `wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)`
 
I also got a message in the server logs, that I pasted in the details section of this report.

Thanks for your help!
