### ISSUE TITLE
OpenAPI: "published_at" in Entries is defined as "datetime|integer" which isn't valid

### ISSUE THREAD

**Issue by voltagex** [wallabag/wallabag#7731]
In the current version of Wallabag, PATCH /entries/{entry} appears to have a type definition of "datetime|integer"

You could use 

```
published_at:
  type: object
  additionalProperties:
    oneOf:
      - type: datetime
      - type: integer

```
or something similar, but I don't know how to write that in a way that Nelmio understands.

There's a few other errors too but this is one I could work out how to fix.

My end goal is to use the new doc.json to generate a Python client using https://github.com/openapi-generators/openapi-python-client
