### ISSUE TITLE
epub export failure with exceeding memory limit

### ISSUE THREAD

**Issue by NoAnyLove** [wallabag/wallabag#7735]
### Environment

* **Version**: 2.6.9
* **Installation**: docker image
* **PHP version**: 8.1
* **OS**: Ubuntu 22.04.5
* **Database**: SQLite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: root
    database_password: null
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://placeholder_for_my_domain'
    server_name: 'placeholder for my server name'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: placeholder_for_secret
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: placeholder_for_email
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Wallabag fails to export epub for some web pages, while exporting to other formats works for the same page. `https://www.techradar.com/tablets/remarkable-paper-pro-review` is one of the links that does not work, below is the error log lines from docker container,

```
172.18.0.1 - - [28/Oct/2024:00:18:38 +0000] "GET /assets/images/0/b/0b3afa65/830ecbbe.jpeg HTTP/1.0" 200 897467 "-" "EPub (Version 4.0.6) by A. Grandt"
2024/10/28 00:18:39 [error] 52#52: *169 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/wallabag/vendor/wallabag/phpepub/src/PHPePub/Helpers/ImageHelper.php on line 306PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 163840 bytes) in /var/www/wallabag/vendor/composer/ClassLoader.php on line 576" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /export/1992.epub HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "placeholder_for_my_domain", referrer: "https://placeholder_for_my_domain/view/1992"
```

I'm not familiar with php, my best guess is one of the libraries does not work well with certain images, or probably the image conversion generated malformed data. In this case, the `/assets/images/0/b/0b3afa65/830ecbbe.jpeg` image is most likely the cause of the issue, it was converted from a WebP format image from `https://cdn.mos.cms.futurecdn.net/8m2jUMAJs3jeTVnjsJDckj-1920-80.jpg.webp`.
