### ISSUE TITLE
wallabag:clean-downloaded-images does not work

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#7777]
### Environment

* **Version**:  2.6.10
* **Installation**: from Git
* **PHP version**: 8.1.30
* **OS**: Ubuntu 22.04
* **Database**: MariaDB 
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: wallabag
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    locale: en
    secret: ***
    twofactor_sender: wallabag@deimeke.ruhr
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: ***
    rss_limit: 500
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    domain_name: '***'
    server_name: ***
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    mailer_dsn: 'smtp://127.0.0.1'
  ```
</details>

### What steps will reproduce the bug?

```
# sudo -u www-data bin/console wallabag:clean-downloaded-images --dry-run
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#37
  #message: """
    Attempted to load class "DebugBundle" from namespace "Symfony\Bundle\DebugBundle".\n
    Did you forget a "use" statement for another namespace?
    """
  #code: 0
  #file: "/srv/www/wallabag.deimeke.ruhr/app/AppKernel.php"
  #line: 48
  trace: {
    /srv/www/wallabag.deimeke.ruhr/app/AppKernel.php:48 {
      AppKernel->registerBundles()^
      › if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
      ›     $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
      ›     $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
    }
    /srv/www/wallabag.deimeke.ruhr/vendor/symfony/http-kernel/Kernel.php:446 { …}
    /srv/www/wallabag.deimeke.ruhr/vendor/symfony/http-kernel/Kernel.php:133 { …}
    /srv/www/wallabag.deimeke.ruhr/vendor/symfony/framework-bundle/Console/Application.php:169 { …}
    /srv/www/wallabag.deimeke.ruhr/vendor/symfony/framework-bundle/Console/Application.php:75 { …}
    /srv/www/wallabag.deimeke.ruhr/vendor/symfony/console/Application.php:149 { …}
    /srv/www/wallabag.deimeke.ruhr/bin/console:27 { …}
  }
}
2024-11-04T07:25:46+01:00 [critical] Uncaught Error: Class "Symfony\Bundle\DebugBundle\DebugBundle" not found

```
