### ISSUE TITLE
Nothing logged in prod.log when adding some sites

### ISSUE THREAD

**Issue by shikasta-net** [wallabag/wallabag#7801]
### Environment

* **Version**: 2.6.10
* **Installation**: docker image
* **PHP version**: 8.1.27
* **OS**: Ubuntu 22.04.4
* **Database**: mariadb 10.11

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: xxx
    database_user: xxx
    database_password: xxx
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: xxx
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.domain.uk'
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: xxx
    twofactor_sender: wallabag@domain.uk
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@domain.uk
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: xxx
    rabbitmq_password: xxx
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?
Mainly a problem when trying to debug failing pages, but this happens for ones that scrape ok too:

1. Try to add/re-fetch some pages (examples below)
1. Nothing written to _var/logs/prod.log_
1. Try a adding other page (examples below)
1. Something written to _var/logs/prod.log_

#### Nothing logged for
* https://www.scotsman.com/news/people/man-89-built-his-own-hobbit-house-in-highlands-where-he-lives-almost-entirely-off-grid-3988400
* https://www.garden-products.co.uk/news/growing-under-glass/how-to-grow-grapes-in-a-greenhouse/
* https://www.sciencing.com/measure-conductivity-water-multimeter-8523350/
* http://www.richardspens.com/?page=ref/care/inks.htm

#### Log recorded for
* https://www.remodelista.com/posts/cuban-mop-how-to-use/
* https://www.slenderkitchen.com/recipe/two-ingredient-english-muffins
* https://www.americastestkitchen.com/cooksillustrated/how_tos/6596-how-to-make-a-stovetop-smoker
* https://craftsofnj.org/spill-planes
