### ISSUE TITLE
500 error retrieving certain pages?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [wallabag/wallabag#7879]
Is anyone else having the same issue with these pages? I just went through a large list of various sites to add to WB and only these out of the list give me 500 error. The interesting thing of note is that for example in the GitHub cases, it's not all of GitHub that does it; just some pages.

https://github.com/iBicha/playlet

![image](https://github.com/user-attachments/assets/6ac97ac6-280f-4ea4-bc13-f7612acb6319)

https://github.com/database64128/youtube-dl-wpf

![image](https://github.com/user-attachments/assets/9375f838-591b-4eac-9b02-b59b25220083)

https://marionevado.art/

![image](https://github.com/user-attachments/assets/d291b5ec-bfad-4ea0-b70e-a27cd9f3a8ae)

https://whatsmyrouterip.com/

![image](https://github.com/user-attachments/assets/cb1e3a2b-bd46-4740-9f40-9a293179400b)

Running the WB container: Version: 2.6.10

**Comment by YouveGotMeowxy** [comment]
ping

**Comment by j0k3r** [comment]
Could you please share your server configuration and the parameters.yml from wallabag? Thanks.

**Comment by YouveGotMeowxy** [comment]
@j0k3r 

`parameters.yml` in WallaBag:

```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: mariadb
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: redacted
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.mydomain.com'
    server_name: MyServer
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: redacted
    twofactor_sender: no-reply@mydomain.com
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```

And my Docker environments:

```
    environment:
      TZ: 'America/Chicago'
      MYSQL_ROOT_PASSWORD: 'redacted'
      #MYSQL_ROOT_PASSWORD__FILE: '/run/secrets/PW-MariaDB'
      SYMFONY__ENV__DATABASE_DRIVER: 'pdo_mysql'
      SYMFONY__ENV__DATABASE_HOST: 'mariadb'
      SYMFONY__ENV__DATABASE_PORT: '3306'
      SYMFONY__ENV__DATABASE_NAME: 'wallabag'
      SYMFONY__ENV__DATABASE_USER: 'wallabag'
      SYMFONY__ENV__DATABASE_DATABASE_TABLE_PREFIX: 'wlqm'
      #SYMFONY__ENV__DATABASE_PASSWORD__FILE: '/run/secrets/PW-Wallabag-DB'
      SYMFONY__ENV__DATABASE_PASSWORD: 'redacted'
      #SYMFONY__ENV__DATABASE_CHARSET: 'utf8mb4_unicode_520_ci'
      POPULATE_DATABASE: 'false' # Required, or gets a db connect error
      SYMFONY__ENV__REDIS_HOST: 'redis'
      SYMFONY__ENV__REDIS_PASSWORD_FILE: '/run/secrets/PW-Redis'
      SYMFONY__ENV__TWOFACTOR_AUTH: 'true'
      SYMFONY__ENV__TWOFACTOR_SENDER: 'no-reply@mydomain.com'
      SYMFONY__ENV__FOSUSER_REGISTRATION: 'false'
      SYMFONY__ENV__FOSUSER_CONFIRMATION: 'true'
      SYMFONY__ENV__MAILER__USER: 'no-reply@mydomain.com'
      #SYMFONY__ENV__MAILER_PASSWORD: 'redacted'
      SYMFONY__ENV__MAILER_PASSWORD__FILE: 'PW-Wallabag-Mailer'
      SYMFONY__ENV__FROM__EMAIL: 'no-reply@mydomain.com'
      #SYMFONY__ENV__SECRET: "redacted"
      SYMFONY__ENV__SECRET__FILE: '/run/secrets/Wallabag-Secret'
      SYMFONY__ENV__DOMAIN_NAME: 'https://wallabag.mydomain.com'
      SYMFONY__ENV__SERVER_NAME: 'MyServer'
```
If there's anything else, just let me know. Thanks! :)
