### ISSUE TITLE
wallabag is not displaying base64 encoded images

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabag#7919]
### Environment

* **Version**: 2.6.10
* **Installation**: make install/update
* **PHP version**: 8.2.26
* **OS**: Debian Trixie=testing
* **Database**: mysql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:
</summary>

  ```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: xxx
    database_user: xxx
    database_password: xxxx
    database_path: null
    database_table_prefix: xxxx_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://xxx.example.com'
    locale: de
    secret: xxx
    twofactor_sender: xxx@xxx
    fosuser_registration: false
    fosuser_confirmation: true
    from_email: xxx@xxx
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: xxx
    rabbitmq_password: xxx
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    server_name: xxx.example.com
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    mailer_dsn: 'smtp://127.0.0.1'
  ```
</details>

### What steps will reproduce the bug?

Trying to catch
- https://papertohtml.org/paper?id=d4685c38dbf463a0d6398eafb9944a056af3b0a8
- https://immub.org/noticias/tambor-de-crioula-do-piaui-a-africa-brasileira
while the second one is a JavaScript re-direct to
- https://pub-24ea3407a0f24c8394eadaa45a05aa0c.r2.dev/texto/3984_pt.html?update=ILT

All images are NOT linked with `<img src"http...` but directly encoded as in-html base64 images. While [FTR](https://ftr.fivefilters.net/) could display the images with current site-configs, in wallabag I only see a verrrrrry long literal `<img src="data:image/png;base64,iVBO...`

Screenshot of wallabag UI after the fetch:
![grafik](https://github.com/user-attachments/assets/2e26af4f-f3f8-4da4-ab16-31202ef567c1)
