### ISSUE TITLE
Deprecated message on step 2 of installation on shared hosting

### ISSUE THREAD

**Issue by c-key** [wallabag/wallabag#7927]
### Environment

* **Version**: 2.6.10
* **Installation**: downloading the package for shared hosting
* **PHP version**: 8.4
* **OS**: Debian
* **Database**: MySQL
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  parameters:
    database_driver: pdo_mysql
    database_host: 'xx.xx.xx.xx'
    database_port: '3306'
    database_name: 'xxx'
    database_user: 'xxx'
    database_password: 'xxx'
    database_path: null
    database_table_prefix: 'wallabag_'
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://your-wallabag-instance.wallabag.org'
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

In the second step of the install command: `php bin/console wallabag:install --env=prod`, I got some deprecated messages for one migration, see below.

```
Step 2 of 4: Setting up database.
---------------------------------

 It appears that your database already exists. Would you like to reset it? (yes/          no) [no]:
 > yes

 Dropping database, creating database and schema...

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 28

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 35

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 35

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 45

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 46

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 48

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../app/DoctrineMigrations/Version20170511211659.php on line 54
 Clearing the cache...

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ../vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 183

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ../vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 188

 Database successfully setup.
```
