### ISSUE TITLE
Error Installing Wallabag with

### ISSUE THREAD

**Issue by gray-host** [wallabag/wallabag#8110]
### Environment

* **Version**: 2.6.10
* **Installation**: Docker on Kubernetes
* **PHP version**:  Unsure
* **OS**: Container is running on an Ubuntu Server 24.04.01
* **Database**: Postgresql Created and Managed by CloudNativePG 1.25.1
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: wallabag-cluster-rw
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: {REDACTED}
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://my.walla.instance'
    server_name: 'Wallabag Instance'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null  
```
</details>

### What steps will reproduce the bug?

I've been trying to install Wallabag on by home Kubernetes server and noticed some issues when trying to use an external Postgresql instance managed by cloudnativepg.  Below are my manifest files:

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-cluster
  namespace: wallabag
spec:
  instances: 2
  storage:
    size: 5Gi
  managed:
    roles:
      - name: wallabag
        comment: User for Wallabag Service
        login: true
        passwordSecret:
          name: wallabag-db-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wallabag-db
  namespace: wallabag
spec:
  cluster:
    name: wallabag-cluster
  name: wallabag
  owner: wallabag
  databaseReclaimPolicy: retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-deploy
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag:latest
          env:
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://my.walla.instance
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "wallabag-cluster-rw"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-auth
                  key: password
            - name: SYMFONY__ENV__SERVER_NAME
              value: "Wallabag Instance"
          ports:
            - containerPort: 80
              name: web
```

Using the above and trying to navigate to the instance I received a 500 error from Wallabag, after inspecting the service logs at var/log/prod.log I saw that the issue was as follows: 
`request.CRITICAL: Exception thrown when handling an exception (Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "wallabag_internal_setting" does not exist`
I then tried to run the console command `wallabag:install` within the container to try and determine what the issue was and received this error on step 2 after telling the command to reset the database: 
```
  The command "doctrine:database:drop" generates some errors:                                        
                                                                                                     
  Could not drop database /var/www/wallabag/data/db/wallabag.sqlite for connection named default     
  An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax er  
  ror at or near "/"                                                                                 
  LINE 1: DROP DATABASE /var/www/wallabag/data/db/wallabag.sqlite
```

After manually setting the `database_path` parameter to null and rerunning the command, I was able to complete the install within the container.  After that all subsequent pod restarts seem to be working correctly.  So, I'm confused as to why I had to go through that process within the container when all the other documentation I could find for docker setups haven't needed to touch the parameters file outside of setting the appropriate environment variables.

I know this isn't a conventional install method and the issue could possibly be because of my setup and I could potentially solve it by mounting a custom parameters.yml file to the pod but I wanted to bring it to the teams attention just in case it is an actual bug.  Feel free to close if this seems too niche an issue, as I said I was able to solve it for myself.
