### ISSUE TITLE
[2.6.12 regression] Latin1 instead of UTF-8 used for entries (`Ã`)

### ISSUE THREAD

**Issue by jtagcat** [wallabag/wallabag#8158]
Version: 2.6.12
Installation: docker
Database:     `postgres:16`
Parameters:   Paste the content of your app/config/parameters.yml (hide sensitive stuff if you want)

```
$ psql -U wallabag -l
                                                      List of databases
   Name    |  Owner   | Encoding | Locale Provider |  Collate   |   Ctype    | ICU Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+------------+------------+------------+-----------+-----------------------
 postgres  | wallabag | UTF8     | libc            | en_US.utf8 | en_US.utf8 |            |           | 
 template0 | wallabag | UTF8     | libc            | en_US.utf8 | en_US.utf8 |            |           | =c/wallabag          +
           |          |          |                 |            |            |            |           | wallabag=CTc/wallabag
 template1 | wallabag | UTF8     | libc            | en_US.utf8 | en_US.utf8 |            |           | =c/wallabag          +
           |          |          |                 |            |            |            |           | wallabag=CTc/wallabag
 wallabag  | wallabag | UTF8     | libc            | en_US.utf8 | en_US.utf8 |            |           | 
```

```
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_CHARSET=utf8
      - SYMFONY__ENV__REDIS_HOST=wallabag-redis
      - ...
```
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_charset: utf8
    rabbitmq_host: localhost
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: wallabag-redis
    ...
```

### What steps will reproduce the bug?
1. Add https://kultuur.err.ee/1609668506/kai-vaartnou-kui-lugemine-pole-monus-siis-mis-ta-uldse-enam-on
2. Title: `Kai VÃ¤Ã¤rtnÃµu: kui lugemine pole mÃµnus, siis mis ta Ã¼ldse enam on?` Content: `Palju Ãµnne, nÃ¤dal...` Expected: as in article (Kai Väärtnõu...)
