### ISSUE TITLE
Some imported URL completely breaks template rendering due to an unserialization error

### ISSUE THREAD

**Issue by jangxx** [wallabag/wallabag#8184]
### Environment

* **Version**: 2.6.12
* **Installation**: docker image
* **PHP version**: 8.1.27 (from running `php -v` in the docker container)
* **OS**: Linux
* **Database**: PostgreSQL
* **Parameters**: 

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_pgsql
    database_host: db
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: wallaroot
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: # redacted
    server_name: # redacted
    mailer_dsn: # redacted
    locale: en
    secret: # redacted
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: # redacted
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

I'm trying to import around 800 links from Pocket now that they're closing down. Unfortunately, while the URLs seem to import fine, I can't actually look at any of them, since opening the list of entries only shows an error message:

```
500: Internal Server Error
An exception has been thrown during the rendering of a template ("Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 695 of 1215 bytes'").
```

![error screenshot](https://i.imgur.com/rH3bnXz.png)

Looking at the log output, I can't see which URL is exactly the culprit, but looking at the _prod.log_ file, the error does produce the log entry:

```
[2025-05-22T22:03:41.337590+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 695 of 1215 bytes'")." at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig line 81 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 695 of 1215 bytes'\"). at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig:81)\n[previous exception] [object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 695 of 1215 bytes' at /var/www/wallabag/vendor/doctrine/dbal/src/Types/ConversionException.php:115)"} []
```

I would really love to switch to wallabag now that Pocket is closing down, so I hope you can fix this quickly. Thanks!
