### ISSUE TITLE
"Could not find driver" during update

### ISSUE THREAD

**Issue by mart-e** [wallabag/wallabag#8201]
### Environment

* **Version**: 2.6.12
* **Installation**: manual
* **PHP version**: 7.4
* **OS**: Debian bullseye
* **Database**: sqllite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    locale: en
    secret: <redacted>
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    domain_name: 'https://read.mart-e.be'
    server_name: 'mart-e read list'
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
    mailer_dsn: 'smtp://127.0.0.1'
  ```
</details>

### What steps will reproduce the bug?

Update the service from (old?) to 2.6.12
```
# su - www-data
$ make update
…
Updating the "app/config/parameters.yml" file
> bin/console cache:clear --no-warmup

In ExceptionConverter.php line 83:

  An exception occurred in the driver: could not find driver


In Exception.php line 24:

  could not find driver


In Driver.php line 43:

  could not find driver


Script bin/console cache:clear --no-warmup handling the post-cmd event returned with error code 1
Script @post-cmd was called via post-install-cmd
make: *** [GNUmakefile:24: update] Error 1
```

I can access wallabag but when I try to add an article from wallabager or fetch my articles from android, I get an error
```
2025/05/26 11:32:06 [error] 29595#29595: *1731027 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/srv/web/read.mart-e.be/wallabag/var/cache/prod/doctrine/orm/Proxies/__CG__WallabagUserBundleEntityUser.php): failed to open stream: No such file or directory in /srv/web/read.mart-e.be/wallabag/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php on line 199PHP message: PHP Fatal error:  require(): Failed opening required '/srv/web/read.mart-e.be/wallabag/var/cache/prod/doctrine/orm/Proxies/__CG__WallabagUserBundleEntityUser.php' (include_path='.:/usr/share/php') in /srv/web/read.mart-e.be/wallabag/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php on line 199" while reading response header from upstream, client: <redacted>, server: read.mart-e.be, request: "POST /oauth/v2/token HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "read.mart-e.be"
```

Thank you

<details>
  <summary>edit: longer example of error when running <code>cache:clean</code></summary>

```
$ php bin/console cache:clear --env=prod -vv

 // Clearing the cache for the prod environment with debug false

 // Clearing outdated warmup directory...

 // Warming up cache...


In ExceptionConverter.php line 83:

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred in the driver: could not find driver


Exception trace:
  at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:83
 Doctrine\DBAL\Driver\API\SQLite\ExceptionConverter->convert() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:1976
 Doctrine\DBAL\Connection->handleDriverException() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:1924
 Doctrine\DBAL\Connection->convertException() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:385
 Doctrine\DBAL\Connection->connect() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:458
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:416
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/dbal/src/Connection.php:323
 Doctrine\DBAL\Connection->getDatabasePlatform() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php:876
 Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php:631
 Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php:160
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:343
 Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:207
 Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:96
 Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() at /srv/web/read.mart-e.be/wallabag/vendor/doctrine/doctrine-bundle/CacheWarmer/DoctrineMetadataCacheWarmer.php:51
 Doctrine\Bundle\DoctrineBundle\CacheWarmer\DoctrineMetadataCacheWarmer->doWarmUp() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/framework-bundle/CacheWarmer/AbstractPhpFileCacheWarmer.php:49
 Symfony\Bundle\FrameworkBundle\CacheWarmer\AbstractPhpFileCacheWarmer->warmUp() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:97
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/http-kernel/Kernel.php:631
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/http-kernel/Kernel.php:136
 Symfony\Component\HttpKernel\Kernel->boot() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/http-kernel/Kernel.php:153
 Symfony\Component\HttpKernel\Kernel->reboot() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:189
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/console/Application.php:1039
 Symfony\Component\Console\Application->doRunCommand() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/console/Application.php:275
 Symfony\Component\Console\Application->doRun() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/web/read.mart-e.be/wallabag/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /srv/web/read.mart-e.be/wallabag/bin/console:27
```

</details>
