### ISSUE TITLE
error 500 on fresh install [critical] Uncaught Error: Class "Symfony\Bundle\DebugBundle\DebugBundle" not found

### ISSUE THREAD

**Issue by eBug** [wallabag/wallabag#8226]
### Environment

* **Version**: 2.6
* **Installation**:
* **PHP version**: 8.2
* **OS**: Debian 12
* **Database**: MySql
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  # This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wb
    database_password: xeec3Eey
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wb.gargantilla.net'
    server_name: ovh
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: 'ztrhzrsrjeyt(§"èjsjrzyjtz1234'
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: redis
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
    rss_limit: 50

  ```
</details>
