### ISSUE TITLE
Issues when importing Pocket CSV feed

### ISSUE THREAD

**Issue by sunilnc** [wallabag/wallabag#8268]
Version:      2.6.13
Installation: Docker image
PHP version:  Unknown
OS: Rasbian OS Lite x64
Database:   I think SQLite

Description of issue:

I have exported my Pocket feeds into a CSV.
When I attempt to import this into Wallabag, it times out and only pulls a subset of the roughly 1,300 articles I have saved.
I have tried to repeat this process multiple times, wiping the feeds each time beforehand to no avail.
It always imports a random amount.

Since then, I have conducted a quick Google search and used an online tool to convert the CSV file into an Instapaper-ready feed, but I am still encountering the same issue.

This is a link to the tool FWIW: https://benjaminoakes.github.io/pocket-to-wallabag/

**Comment by j0k3r** [comment]
Have you tried to increase the memory allocated to PHP using `-e PHP_MEMORY_LIMIT=...`?

**Comment by sunilnc** [comment]
I have not tried that.
Would I do that in Docker Compose or within Wallabag? 

This is my docker compose file, I can't see such an entry:
```
version: '3.3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      # Database choice: pdo_sqlite, pdo_mysql, or pdo_pgsql
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      # For SQLite, the path is relative to /var/www/wallabag/data/db/
      - SYMFONY__ENV__DATABASE_PATH=/var/www/wallabag/data/db/wallabag.sqlite
      # If using MySQL/MariaDB or PostgreSQL, you'd uncomment and set these:
      # - SYMFONY__ENV__DATABASE_HOST=db # Or the IP/hostname of your DB server
      # - SYMFONY__ENV__DATABASE_PORT=3306 # Or 5432 for PostgreSQL
      # - SYMFONY__ENV__DATABASE_NAME=wallabag
      # - SYMFONY__ENV__DATABASE_USER=wallabag_user
      # - SYMFONY__ENV__DATABASE_PASSWORD=your_strong_password
      # - SYMFONY__ENV__DATABASE_TABLE_PREFIX=wallabag_ # Optional

      # Server name (your Raspberry Pi's IP or a domain name if you have one)
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.0.17:8088
      - SYMFONY__ENV__SERVER_NAME="Wallabag on Raspberry Pi"

      # Other optional settings (see Wallabag documentation for more)
      - SYMFONY__ENV__POPULATOR_USERNAME= # Leave empty if not using a default populators user
      - SYMFONY__ENV__POPULATOR_PASSWORD=
      - SYMFONY__ENV__POPULATOR_NB_ARTICLES=0
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false # Set to true to require email confirmation

    ports:
      - "8088:80" # Map port 8088 on your Pi to port 80 in the container
    volumes:
      - ./data:/var/www/wallabag/data   # For SQLite database and user data
      - ./images:/var/www/wallabag/web/assets/images # For article images
    restart: unless-stopped
```

**Comment by j0k3r** [comment]
In the `environment:` part, add `PHP_MEMORY_LIMIT` like:

```yaml
version: '3.3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      - PHP_MEMORY_LIMIT=512M
#...
```
