### ISSUE TITLE
Page not rendering correctly

### ISSUE THREAD

**Issue by colfin22** [wallabag/wallabag#8281]
![Image](https://github.com/user-attachments/assets/78b1c614-a636-4163-a322-c6af489034c4)

Running on docker, here is my compose file

````
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_DSN=smtp.gmail.com
      - SYMFONY__ENV__FROM_EMAIL=wallabag@xxxxxx.net
      - SYMFONY__ENV__DOMAIN_NAME=https://read-later.xxxxxx.net
      - SYMFONY__ENV__SERVER_NAME="XXXs Wallabag Server"
    ports:
      - "80:80"
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--innodb_initialized"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.254,nolock,soft,rw"
      device: ":/mnt/MainPool/wallabag/app"

  db_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.254,nolock,soft,rw"
      device: ":/mnt/MainPool/wallabag/db"
````
