### ISSUE TITLE
Embed YouTube video player in article view

### ISSUE THREAD

**Issue by bcutter** [wallabag/wallabag#8288]
**Is your feature request related to a problem? Please describe.**
YouTube links always require to follow the external link to actually get to the content.

**Describe the solution you'd like**
Embed the YT video player. Not just a full sized preview image, but the actual player. This way one does not need to leave Wallabag.

**Describe alternatives you've considered**
-

**Additional context**
Currently with v2.6.13:
![Image](https://github.com/user-attachments/assets/68e25968-3a1a-49e5-b8d7-410162015f4a)

Mockup of desired look:

![Image](https://github.com/user-attachments/assets/81aa7c6b-d494-4a3b-ae17-014ca5461d37)

**Comment by nicosomb** [comment]
Hmm that's strange. I tried locally and the video is embedded. Can you give us details of your installation?

**Comment by bcutter** [comment]
Ah okay so it actually should work. ~~Feature request~~ -> Bug report.

**Sure, which information precisely do you need?**

It appears in all browsers (Firefox, Safari, ...) - missing video - so probably a server thing?

**Comment by nicosomb** [comment]
Yes, send us your server configuration.

**Comment by bcutter** [comment]
Ehm, not sure what you mean with "server configuration". I pulled this from the bug report issue template, hopefully this is what you need:

### Environment

* **Version**: 2.6.13
* **Installation**: Git clone
* **PHP version**: 8.3.22
* **OS**: Raspberry Pi OS (Debian 12)
* **Database**: MariaDB 10.11.11
* **Parameters**: -

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: xxx
    database_password: xxx
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://my.domain.name'
    server_name: my.domain.name
    mailer_dsn: 'smtp://xxx:xxx@xxx:587?encryption=tls&auth_mode=login'
    locale: de
    secret: xxx
    twofactor_sender: xxx
    fosuser_registration: false
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: xxx
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: unix
    redis_host: localhost
    redis_port: 6379
    redis_path: /var/run/redis-wallabag/redis-wallabag.sock
    redis_password: null
    sentry_dsn: null
  ```
</details>


Nothing in `/var/www/wallabag/var/logs/prod.log` neither at the time of storing a YT link (using Wallabagger Firefox extension) nor when viewing a YT link in Wallabag. Completely no idea what's wrong here. I also disabled any browser or network based privacy addons or DNS filters - but there's no YT video shown.

The interesting thing is, looking at the HTML code of the page, it seems like the embedded video should be there:

![Image](https://github.com/user-attachments/assets/f3912038-846b-4507-a648-f56dfcf0b0e0)

I can also manually open the URL (https://www.youtube.com/embed/QumXVbpw8YU?feature=oembed).

So maybe you can find anything in here (nginx / reverse proxy configuration file for Wallabag)? Is something "overblocking" Wallabag's content maybe?

EDIT: Found it on my own. Security Header settings following https://securityheaders.com rendered parts inoperable. That's what the browsers error console clearly indicated with
```
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource (media-src) auf data: blockiert, da sie gegen folgende Direktive verstößt: "default-src 'self'" 92
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource (frame-src) auf https://www.youtube.com/embed/QumXVbpw8YU?feature=oembed blockiert, da sie gegen folgende Direktive verstößt: "default-src 'self'" 92
Error: Promised response from onMessage listener went out of scope
```

I changed the former CSP

```
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src 'self' data:; connect-src *; frame-ancestors 'none';" always;
```

now to

```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src 'self' data:; connect-src *; frame-src *; media-src * data: blob:; frame-ancestors 'none';" always;
```

and et voila:

![Image](https://github.com/user-attachments/assets/72dc90f7-5351-44e4-b394-a8f0a5dfb546)

Summary:
- It was an overblocking by a strict CSP.
- Everything fine on Wallabag side.
- Now the security header check is downgraded from an A+ to an A because of the `unsafe-inline` setting which seems to be necessary (obviously) for Wallabag to work correctly.
![Image](https://github.com/user-attachments/assets/57eba0ef-f543-4883-979a-a03b574d67a3)

Pardon for the unnecessary noise.
